package com.likhibi.keyboard

import android.content.Context
import android.util.Log

class NagameseOfflineEngine(private val context: Context) {

    // Thread-safe in-memory cache for past Gemini API results (LRU cache representation)
    private val geminiCache = object : LinkedHashMap<String, List<String>>(100, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, List<String>>?): Boolean {
            return size > 150 // Keep up to 150 unique context prediction entries
        }
    }

    // Learned user vocabulary (added during the current typing sessions to personalize predictions)
    private val userWords = mutableMapOf<String, Int>()

    // Learned user bigrams (added as the user types transitions to personalize next-word predictions)
    private val userBigrams = mutableMapOf<String, MutableMap<String, Int>>()

    // Local high-frequency vocabulary list of EXACTLY 430+ commonly used Nagamese words based on Bible & Grammar texts
    private val localDictionary: Map<String, Int> by lazy {
        mapOf(
            "moi" to 100,
        "tumi" to 98,
        "laga" to 95,
        "tai" to 95,
        "ase" to 95,
        "ami" to 92,
        "morom" to 90,
        "hobo" to 90,
        "isor" to 90,
        "moilaga" to 90,
        "amikhan" to 90,
        "apuni" to 90,
        "asu" to 90,
        "aro" to 90,
        "bhal" to 90,
        "te" to 90,
        "apunilaga" to 88,
        "pora" to 88,
        "toi" to 88,
        "hoise" to 88,
        "probhu" to 88,
        "jisu" to 88,
        "paani" to 88,
        "bishi" to 87,
        "etu" to 86,
        "itu" to 86,
        "bissi" to 86,
        "to" to 86,
        "khrist" to 86,
        "ke" to 86,
        "aru" to 86,
        "bisi" to 86,
        "nijor" to 85,
        "biswas" to 85,
        "jabo" to 85,
        "eneka" to 85,
        "ahise" to 85,
        "bhat" to 85,
        "tumikhan" to 85,
        "hoi" to 85,
        "amilaga" to 85,
        "kelemane" to 85,
        "taikhan" to 85,
        "nai" to 85,
        "naam" to 85,
        "amen" to 85,
        "koise" to 85,
        "khor" to 85,
        "kori" to 85,
        "bia" to 84,
        "sob" to 84,
        "hoilebi" to 84,
        "lagise" to 84,
        "na" to 84,
        "lagibo" to 84,
        "lage" to 84,
        "kam" to 84,
        "ki" to 83,
        "kile-koile" to 82,
        "hobole" to 82,
        "ghor" to 82,
        "jaise" to 82,
        "swarg" to 82,
        "tinehoile" to 82,
        "sahaay" to 82,
        "paap" to 82,
        "rasta" to 82,
        "ahibole" to 82,
        "dibi" to 82,
        "thakibo" to 82,
        "dise" to 82,
        "dibo" to 82,
        "tenehoile" to 82,
        "aji" to 82,
        "ekta" to 82,
        "taka" to 82,
        "khan" to 82,
        "pabo" to 82,
        "olop" to 82,
        "khusi" to 82,
        "pobitro" to 82,
        "dusra" to 82,
        "jibon" to 82,
        "nisina" to 82,
        "abi" to 82,
        "paise" to 82,
        "dangor" to 82,
        "tailaga" to 82,
        "nisena" to 82,
        "manu" to 81,
        "kene" to 81,
        "din" to 80,
        "he" to 80,
        "kore" to 80,
        "thakise" to 80,
        "naloijabi" to 80,
        "loise" to 80,
        "taike" to 80,
        "toilaga" to 80,
        "kintu" to 80,
        "itiya" to 80,
        "kotha" to 80,
        "alag" to 80,
        "gaon" to 80,
        "ma" to 80,
        "homoy" to 80,
        "janise" to 80,
        "putro" to 80,
        "dam" to 80,
        "koridibi" to 80,
        "kobo" to 80,
        "sosa" to 80,
        "lagiase" to 80,
        "lobo" to 80,
        "baba" to 80,
        "bhi" to 80,
        "chutu" to 80,
        "pare" to 80,
        "khabar" to 80,
        "pakila" to 80,
        "ahibi" to 80,
        "school" to 80,
        "nimite" to 80,
        "aur" to 80,
        "thake" to 80,
        "ahile" to 80,
        "prithibi" to 80,
        "bi" to 80,
        "eta" to 80,
        "jabe" to 80,
        "kali" to 80,
        "gari" to 80,
        "nohoile" to 79,
        "swarg-te" to 78,
        "pobitro-ase" to 78,
        "kapra" to 78,
        "thakia" to 78,
        "prithibi-tebi" to 78,
        "agote" to 78,
        "dur" to 78,
        "jineka" to 78,
        "desh" to 78,
        "maaf-koridibi" to 78,
        "ketiya" to 78,
        "duita" to 78,
        "bosor" to 78,
        "bujhibo" to 78,
        "dada" to 78,
        "pahar" to 78,
        "paap-khanke" to 78,
        "rat" to 78,
        "khabo" to 78,
        "dusrakhan" to 78,
        "sasa" to 78,
        "bhal-hoise" to 78,
        "hoibo" to 78,
        "ketap" to 78,
        "maaf-kori" to 78,
        "bukha" to 78,
        "anondo" to 78,
        "thakibi" to 78,
        "naya" to 78,
        "bajar" to 78,
        "jaldi" to 78,
        "likhibo" to 78,
        "porikhate" to 78,
        "rakhibi" to 78,
        "dukan" to 78,
        "misa" to 78,
        "bujhi" to 78,
        "bujhise" to 78,
        "saab" to 78,
        "naki" to 77,
        "tinta" to 76,
        "son" to 76,
        "atma" to 76,
        "didi" to 76,
        "rakhise" to 76,
        "hataikena" to 76,
        "hunise" to 76,
        "safa" to 76,
        "sopon" to 76,
        "mon" to 76,
        "sakri" to 76,
        "soku" to 76,
        "shakti" to 76,
        "deshke" to 76,
        "poribo" to 76,
        "pise" to 76,
        "boini" to 76,
        "porise" to 76,
        "cha" to 76,
        "aaste" to 76,
        "bhai" to 76,
        "di-thakibi" to 76,
        "huni" to 76,
        "loijabi" to 76,
        "hapta" to 76,
        "hoile" to 76,
        "khub" to 76,
        "kile" to 76,
        "rakhibo" to 76,
        "pisot" to 76,
        "kaam" to 76,
        "bia-pora" to 76,
        "mukh" to 76,
        "jun" to 76,
        "kunba" to 76,
        "gaot" to 75,
        "khotom" to 75,
        "sidha" to 75,
        "saru" to 75,
        "khali" to 75,
        "jada" to 75,
        "sobse" to 75,
        "koi" to 75,
        "prarthona" to 75,
        "thanda" to 75,
        "gorom" to 75,
        "purana" to 75,
        "uporte" to 75,
        "likhise" to 75,
        "bemar" to 75,
        "jaan" to 75,
        "jano" to 75,
        "santi" to 75,
        "kuribo" to 75,
        "jinda" to 75,
        "jaane" to 75,
        "hode" to 75,
        "doya" to 75,
        "kun" to 75,
        "likhi" to 75,
        "asirbad" to 75,
        "kheti" to 75,
        "sommaan" to 74,
        "path" to 74,
        "basta" to 74,
        "dhormo" to 74,
        "sisa" to 74,
        "rong" to 74,
        "pathar" to 74,
        "nodi" to 74,
        "girja" to 74,
        "rupiya" to 74,
        "sithi" to 74,
        "hawa" to 74,
        "hajar" to 74,
        "ghonta" to 74,
        "khosi" to 74,
        "suraj" to 74,
        "samoy" to 74,
        "suli" to 74,
        "beli" to 74,
        "kan" to 74,
        "itube" to 74,
        "nak" to 74,
        "biswasi" to 74,
        "boros" to 74,
        "mah" to 74,
        "chiti" to 74,
        "hunibo" to 74,
        "somoi" to 74,
        "tebi" to 74,
        "kuri" to 74,
        "kora" to 74,
        "rakhi" to 74,
        "sador" to 74,
        "sarita" to 74,
        "kalkar" to 74,
        "pashta" to 74,
        "logot" to 73,
        "pichete" to 73,
        "karone" to 73,
        "pai" to 73,
        "jaga" to 73,
        "kineka" to 73,
        "thaka" to 73,
        "matibo" to 72,
        "kamabo" to 72,
        "bepar" to 72,
        "hahise" to 72,
        "hahi" to 72,
        "uthise" to 72,
        "india" to 72,
        "sabun" to 72,
        "kobi" to 72,
        "lamba" to 72,
        "uthibo" to 72,
        "bepari" to 72,
        "khelise" to 72,
        "bonai" to 72,
        "kamase" to 72,
        "notun" to 72,
        "mati" to 72,
        "buri" to 72,
        "sinikise" to 72,
        "kinise" to 72,
        "kinibo" to 72,
        "chota" to 72,
        "use" to 72,
        "matise" to 72,
        "sinikibo" to 72,
        "banaibo" to 72,
        "kuribole" to 72,
        "pani" to 72,
        "dhormik" to 72,
        "sat-ta" to 72,
        "ful" to 72,
        "kripa" to 72,
        "bhalmon" to 72,
        "minit" to 72,
        "uddhar" to 72,
        "gahori" to 72,
        "kolom" to 72,
        "murgi" to 72,
        "khelibo" to 72,
        "kros" to 72,
        "banaise" to 72,
        "jai" to 72,
        "chabi" to 72,
        "duri" to 72,
        "megh" to 72,
        "dos-ta" to 72,
        "tin" to 72,
        "bura" to 72,
        "tini" to 72,
        "diye" to 72,
        "at-ta" to 72,
        "dukani" to 72,
        "jinis" to 71,
        "nohoi" to 71,
        "kote" to 71,
        "sundor" to 71,
        "komti" to 71,
        "thik" to 71,
        "hodai" to 70,
        "kitia" to 70,
        "napare" to 70,
        "ghoraise" to 70,
        "saakhi" to 70,
        "dhorj" to 70,
        "rokto" to 70,
        "kama" to 70,
        "ghoraibo" to 70,
        "moron" to 70,
        "uthi" to 70,
        "khana" to 70,
        "sini" to 70,
        "semeka" to 70,
        "nak-te" to 70,
        "toh" to 70,
        "dokari" to 70,
        "ghurise" to 70,
        "bohise" to 70,
        "hahibo" to 70,
        "sobji" to 70,
        "potise" to 70,
        "biya" to 70,
        "potibo" to 70,
        "doot" to 70,
        "hudibo" to 70,
        "saitan" to 70,
        "namro" to 70,
        "andha" to 70,
        "bohibo" to 70,
        "gas" to 70,
        "git" to 70,
        "chalak" to 70,
        "kheli" to 70,
        "mas" to 70,
        "marise" to 70,
        "kiba" to 70,
        "bhabobadi" to 70,
        "hudise" to 70,
        "tufan" to 70,
        "khirki" to 70,
        "tara" to 70,
        "ghuribo" to 70,
        "unish" to 70,
        "kukur" to 70,
        "naw-ta" to 70,
        "bali" to 70,
        "ghuri" to 70,
        "banai" to 70,
        "bijli" to 70,
        "bona" to 70,
        "kini" to 70,
        "samundar" to 70,
        "maribo" to 70,
        "bithobi" to 70,
        "sekon" to 70,
        "poti" to 70,
        "kuribi" to 69,
        "bole" to 69,
        "tate" to 69,
        "joldi" to 69,
        "judi" to 69,
        "kiman" to 69,
        "motlob" to 69,
        "etiya" to 69,
        "poisa" to 69,
        "modot" to 69,
        "hisab" to 69,
        "bohut" to 69,
        "paribo" to 69,
        "mat" to 68,
        "biral" to 68,
        "kela" to 68,
        "jani" to 68,
        "komola" to 68,
        "kandise" to 68,
        "kandibo" to 68,
        "loi" to 68,
        "of" to 68,
        "ahe" to 68,
        "shuru" to 68,
        "tati" to 68,
        "kula" to 68,
        "pukhur" to 68,
        "norko" to 68,
        "katibo" to 68,
        "katise" to 68,
        "bohi" to 68,
        "tak" to 68,
        "tu" to 68,
        "sapibo" to 68,
        "nodit" to 68,
        "dan" to 68,
        "famous" to 68,
        "palaise" to 68,
        "hosa" to 68,
        "koribole" to 68,
        "mari" to 68,
        "asol" to 68,
        "torkari" to 68,
        "nodik" to 68,
        "dal" to 68,
        "lobi" to 68,
        "moike" to 68,
        "pat" to 68,
        "hati" to 68,
        "billi" to 68,
        "poila" to 68,
        "diya" to 68,
        "asurit" to 68,
        "am" to 68,
        "palabo" to 68,
        "sapise" to 68,
        "asele" to 68,
        "pakhir" to 68,
        "goru" to 68,
        "kahani" to 67,
        "dukh" to 67,
        "sheher" to 67,
        "pura" to 67,
        "jabole" to 67,
        "naga" to 67,
        "ekjon" to 67,
        "wala" to 67,
        "kitab" to 67,
        "majote" to 67,
        "logote" to 67,
        "kilekoile" to 67,
        "bhitor" to 67,
        "sathi" to 67,
        "kosis" to 66,
        "ek" to 66,
        "dibole" to 66,
        "sai" to 66,
        "phone" to 66,
        "hali" to 66,
        "najane" to 66,
        "kurile" to 66,
        "nagaland" to 66,
        "lula" to 66,
        "goli" to 66,
        "chagol" to 66,
        "khai" to 66,
        "time" to 66,
        "hahu" to 66,
        "ghora" to 66,
        "bhasa" to 66,
        "aste" to 66,
        "muri" to 66,
        "the" to 66,
        "takot" to 66,
        "lai-pat" to 66,
        "national" to 66,
        "bacha" to 66,
        "lorai" to 66,
        "khal" to 66,
        "eke" to 66,
        "sira" to 66,
        "mili" to 66,
        "thakile" to 66,
        "likha" to 66,
        "shanti" to 66,
        "palai" to 66,
        "ta" to 66,
        "duniya" to 66,
        "khushi" to 66,
        "tan" to 66,
        "kati" to 66,
        "idea" to 65,
        "thakisele" to 65,
        "koribo" to 65,
        "sabi" to 65,
        "online" to 65,
        "paan" to 65,
        "tamul" to 65,
        "di" to 65,
        "shawl" to 65,
        "sapha" to 65,
        "gana" to 65,
        "sapna" to 65,
        "masala" to 65,
        "card" to 65,
        "bonabole" to 64,
        "bodli" to 64,
        "mous" to 64,
        "maane" to 64,
        "jitia" to 64,
        "movie" to 64,
        "saal" to 64,
        "bhoi" to 64,
        "south" to 64,
        "age" to 64,
        "festival" to 64,
        "kothal" to 64,
        "bhalu" to 64,
        "aiya" to 64,
        "anaras" to 64,
        "tribe" to 64,
        "moris" to 64,
        "lichu" to 64,
        "hoisele" to 64,
        "bilahi" to 64,
        "mokokchung" to 64,
        "bujhai" to 64,
        "photo" to 64,
        "aram" to 64,
        "capital" to 64,
        "dhania" to 64,
        "koribi" to 64,
        "bosti" to 64,
        "eku" to 64,
        "dhorom" to 64,
        "design" to 63,
        "mane" to 63,
        "koile" to 63,
        "indian" to 63,
        "company" to 63,
        "number" to 63,
        "sonman" to 63,
        "bo" to 63,
        "town" to 63,
        "phale" to 63,
        "dorkar" to 63,
        "asan" to 63,
        "direct" to 63,
        "information" to 63,
        "bhabona" to 63,
        "ekdom" to 63,
        "doctor" to 63,
        "kohima" to 63,
        "bhabe" to 63,
        "bahar" to 63,
        "ulai" to 63,
        "jane" to 63,
        "bhag" to 63,
        "chinta" to 63,
        "dimapur" to 63,
        "daam" to 63,
        "mangso" to 62,
        "choukh" to 62,
        "korile" to 62,
        "iman" to 62,
        "jor" to 62,
        "ada" to 62,
        "pibole" to 62,
        "laptop" to 62,
        "gaw" to 62,
        "titia" to 62,
        "jabi" to 62,
        "khobor" to 62,
        "district" to 62,
        "problem" to 62,
        "tel" to 62,
        "office" to 62,
        "state" to 62,
        "dudh" to 62,
        "rohun" to 62,
        "zunheboto" to 62,
        "culture" to 62,
        "kopou" to 62,
        "supari" to 62,
        "bank" to 62,
        "kura" to 62,
        "janwar" to 62,
        "naspati" to 62,
        "ahibo" to 62,
        "jodi" to 62,
        "milai" to 62,
        "sorkar" to 62,
        "peaj" to 62,
        "africa" to 61,
        "porha" to 61,
        "ghas" to 61,
        "dile" to 61,
        "special" to 61,
        "nalage" to 61,
        "himot" to 61,
        "normal" to 61,
        "korishe" to 61,
        "dikhe" to 61,
        "moja" to 61,
        "jinish" to 61,
        "main" to 61,
        "usor" to 61,
        "dorkari" to 61,
        "huwa" to 61,
        "check" to 61,
        "chola" to 61,
        "sabole" to 61,
        "lagai" to 61,
        "local" to 61,
        "ac" to 61,
        "try" to 61,
        "korise" to 61,
        "british" to 61,
        "dikhai" to 61,
        "myanmar" to 61,
        "nagamese" to 61,
        "bonabo" to 61,
        "data" to 61,
        "group" to 61,
        "berabole" to 61,
        "phol" to 61,
        "mitha" to 60,
        "nakore" to 60,
        "wapas" to 60,
        "system" to 60,
        "tasty" to 60,
        "research" to 60,
        "thakibole" to 60,
        "joma" to 60,
        "pillow" to 60,
        "bar" to 60,
        "howa" to 60,
        "suku" to 60,
        "computer" to 60,
        "asia" to 60,
        "chari" to 60,
        "nahoi" to 60,
        "kagos" to 60,
        "farak" to 60,
        "yaad" to 60,
        "bisari" to 60,
        "nakuribi" to 60,
        "coffee" to 60,
        "film" to 60,
        "party" to 60,
        "social" to 60,
        "sukha" to 60,
        "english" to 60,
        "untcha" to 60,
        "niyam" to 60,
        "empire" to 60,
        "fan" to 60,
        "mithai" to 60,
        "besih" to 60,
        "kobole" to 60,
        "japan" to 60,
        "korim" to 60,
        "raja" to 60,
        "lobole" to 60,
        "napai" to 60,
        "room" to 60,
        "pej" to 60,
        "maiki" to 60,
        "golti" to 60,
        "baigan" to 60,
        "website" to 60,
        "chini" to 60,
        "depend" to 60,
        "ghiu" to 60,
        "internet" to 59,
        "hudi" to 59,
        "de" to 59,
        "hikibole" to 59,
        "gundh" to 59,
        "nathake" to 59,
        "animal" to 59,
        "police" to 59,
        "theory" to 59,
        "city" to 59,
        "australia" to 59,
        "job" to 59,
        "chokma" to 59,
        "khabole" to 59,
        "hospital" to 59,
        "control" to 59,
        "scientist" to 59,
        "china" to 59,
        "karon" to 59,
        "on" to 59,
        "line" to 59,
        "plan" to 59,
        "war" to 59,
        "kurisele" to 59,
        "america" to 59,
        "besi" to 59,
        "cheese" to 59,
        "hath" to 59,
        "manai" to 59,
        "nimok" to 59,
        "para" to 59,
        "mori" to 59,
        "pizza" to 59,
        "new" to 59,
        "pet" to 59,
        "jowab" to 59,
        "se" to 59,
        "haiku" to 59,
        "certificate" to 59,
        "mile" to 59,
        "paper" to 59,
        "kinika" to 59,
        "style" to 59,
        "code" to 59,
        "safe" to 59,
        "bhoot" to 59,
        "bird" to 59,
        "europe" to 59,
        "rakhe" to 59,
        "awaj" to 59,
        "anubhav" to 59,
        "business" to 59,
        "mobile" to 59,
        "mota" to 59,
        "current" to 59,
        "un" to 59,
        "proshno" to 59,
        "rakhibole" to 59,
        "important" to 58,
        "and" to 58,
        "ketiabi" to 58,
        "power" to 58,
        "rakha" to 58,
        "machine" to 58,
        "nobel" to 58,
        "halka" to 58,
        "lagi" to 58,
        "gyaan" to 58,
        "pasta" to 58,
        "sele" to 58,
        "taste" to 58,
        "pata" to 58,
        "ai" to 58,
        "proof" to 58,
        "hikai" to 58,
        "aadhar" to 58,
        "jote" to 58,
        "khale" to 58,
        "berai" to 58,
        "apunike" to 58,
        "bondh" to 58,
        "pasant" to 58,
        "bhabi" to 58,
        "llm" to 58,
        "rosgulla" to 58,
        "food" to 58,
        "adat" to 58,
        "who" to 58,
        "le" to 58,
        "assam" to 58,
        "th" to 58,
        "naparibo" to 58,
        "restaurant" to 58,
        "prize" to 58,
        "dui" to 58,
        "philosophy" to 58,
        "video" to 58,
        "dawai" to 58,
        "health" to 58,
        "matha" to 58,
        "government" to 58,
        "station" to 58,
        "form" to 58,
        "bill" to 58,
        "duijon" to 58,
        "department" to 58,
        "jonom" to 58,
        "apply" to 58,
        "council" to 58,
        "world" to 58,
        "free" to 58,
        "majot" to 58,
        "juntu" to 58,
        "northeast" to 58,
        "koikena" to 58,
        "music" to 58,
        "tey" to 57,
        "hotel" to 57,
        "jongol" to 57,
        "suryo" to 57,
        "pradesh" to 57,
        "arunachal" to 57,
        "norom" to 57,
        "vegan" to 57,
        "nathaka" to 57,
        "game" to 57,
        "faisla" to 57,
        "science" to 57,
        "building" to 57,
        "media" to 57,
        "juice" to 57,
        "manipur" to 57,
        "island" to 57,
        "sabo" to 57,
        "change" to 57,
        "bikhai" to 57,
        "porhibole" to 57,
        "nepal" to 57,
        "you" to 57,
        "jiman" to 57,
        "password" to 57,
        "dimag" to 57,
        "christmas" to 57,
        "lens" to 57,
        "harai" to 57,
        "medinipur" to 57,
        "dekhai" to 57,
        "app" to 57,
        "college" to 57,
        "library" to 57,
        "bengal" to 57,
        "light" to 57,
        "nije" to 57,
        "gb" to 57,
        "digdar" to 57,
        "konyak" to 57,
        "dikhibole" to 57,
        "kala" to 57,
        "jona" to 57,
        "meme" to 57,
        "official" to 57,
        "bhor" to 57,
        "hissa" to 57,
        "east" to 57,
        "khula" to 57,
        "chinese" to 57,
        "hoshiar" to 57,
        "ja" to 57,
        "thaki" to 57,
        "dhanyabaad" to 57,
        "ekbar" to 57,
        "north" to 57,
        "account" to 57,
        "post" to 57,
        "ghanta" to 57,
        "bachai" to 57,
        "service" to 57,
        "yate" to 57,
        "hudile" to 57,
        "diary" to 57,
        "cholai" to 57,
        "sol" to 57,
        "great" to 57,
        "bonaise" to 57,
        "bujhibole" to 56,
        "valley" to 56,
        "itihas" to 56,
        "practice" to 56,
        "pohor" to 56,
        "raat" to 56,
        "prothom" to 56,
        "poribar" to 56,
        "message" to 56,
        "borof" to 56,
        "football" to 56,
        "team" to 56,
        "nichete" to 56,
        "ao" to 56,
        "especially" to 56,
        "korisile" to 56,
        "sorkari" to 56,
        "traditional" to 56,
        "sikkim" to 56,
        "likhibole" to 56,
        "kobita" to 56,
        "century" to 56,
        "process" to 56,
        "cake" to 56,
        "common" to 56,
        "khatra" to 56,
        "kunu" to 56,
        "program" to 56,
        "dish" to 56,
        "area" to 56,
        "lal" to 56,
        "screen" to 56,
        "kimaan" to 56,
        "hekh" to 56,
        "patla" to 56,
        "jitu" to 56,
        "park" to 56,
        "chihna" to 56,
        "license" to 56,
        "ekla" to 56,
        "mohina" to 56,
        "khel" to 56,
        "bus" to 56,
        "public" to 56,
        "raj" to 56,
        "sipahi" to 56,
        "sal" to 56,
        "boga" to 56,
        "utu" to 56,
        "private" to 56,
        "history" to 56,
        "tea" to 56,
        "jui" to 56,
        "aha" to 56,
        "ghumti" to 56,
        "neanderthal" to 56,
        "personal" to 56,
        "hoijabo" to 56,
        "pakistan" to 56,
        "option" to 56,
        "topic" to 56,
        "maph" to 56,
        "details" to 56,
        "gham" to 56,
        "suvidha" to 56,
        "alexander" to 56,
        "art" to 56,
        "saman" to 56,
        "side" to 56,
        "email" to 56,
        "kowa" to 56,
        "exercise" to 56,
        "training" to 56,
        "village" to 56,
        "market" to 56,
        "book" to 56,
        "hasi" to 56,
        "usa" to 56,
        "joruri" to 56,
        "type" to 55,
        "report" to 55,
        "cricket" to 55,
        "good" to 55,
        "point" to 55,
        "pari" to 55,
        "climate" to 55,
        "in" to 55,
        "porhi" to 55,
        "natural" to 55,
        "color" to 55,
        "interesting" to 55,
        "exam" to 55,
        "shape" to 55,
        "pathor" to 55,
        "kisim" to 55,
        "prathana" to 55,
        "dikhibo" to 55,
        "student" to 55,
        "technology" to 55,
        "energy" to 55,
        "quality" to 55,
        "conspiracy" to 55,
        "haha" to 55,
        "asar" to 55,
        "hunibole" to 55,
        "sauce" to 55,
        "phojur" to 55,
        "khelibole" to 55,
        "dikhabo" to 55,
        "usorte" to 55,
        "bangladesh" to 55,
        "mongol" to 55,
        "feel" to 55,
        "sanskrit" to 55,
        "facebook" to 55,
        "kinar" to 55,
        "red" to 55,
        "id" to 55,
        "drink" to 55,
        "likhibi" to 55,
        "bhaat" to 55,
        "chemical" to 55,
        "dikhise" to 55,
        "lagabo" to 55,
        "kinibole" to 55,
        "agete" to 55,
        "share" to 55,
        "nathakile" to 55,
        "jagate" to 55,
        "radio" to 55,
        "chocolate" to 55,
        "language" to 55,
        "class" to 55,
        "society" to 55,
        "canada" to 55,
        "colonialism" to 55,
        "scheme" to 55,
        "order" to 55,
        "black" to 55,
        "ink" to 55,
        "phul" to 55,
        "koisile" to 55,
        "future" to 55,
        "recipe" to 55,
        "niche" to 55,
        "loan" to 55,
        "kombucha" to 55,
        "chiriya" to 55,
        "nishchoy" to 55,
        "char" to 55,
        "border" to 55,
        "interest" to 55,
        "blanket" to 55,
        "mana" to 55,
        "porhibo" to 55,
        "dikha" to 55,
        "kunbi" to 55,
        "easter" to 55,
        "dhyan" to 55,
        "manager" to 55,
        "khuli" to 55,
        "address" to 54,
        "university" to 54,
        "tengaa" to 54,
        "no" to 54,
        "nature" to 54,
        "french" to 54,
        "lanka" to 54,
        "table" to 54,
        "cream" to 54,
        "pen" to 54,
        "space" to 54,
        "software" to 54,
        "anibole" to 54,
        "delete" to 54,
        "andhar" to 54,
        "paar" to 54,
        "greek" to 54,
        "likhe" to 54,
        "list" to 54,
        "sharab" to 54,
        "ottoman" to 54,
        "deri" to 54,
        "series" to 54,
        "chara" to 54,
        "popular" to 54,
        "kharcha" to 54,
        "nach" to 54,
        "maas" to 54,
        "test" to 54,
        "google" to 54,
        "bikiri" to 54,
        "itcha" to 54,
        "american" to 54,
        "goal" to 54,
        "character" to 54,
        "train" to 54,
        "general" to 54,
        "essay" to 54,
        "nakoribi" to 54,
        "extra" to 54,
        "kurise" to 54,
        "khong" to 54,
        "application" to 54,
        "pathai" to 54,
        "pot" to 54,
        "ration" to 54,
        "daat" to 54,
        "ahi" to 54,
        "hudibi" to 54,
        "barish" to 54,
        "taxi" to 54,
        "simple" to 54,
        "fermented" to 54,
        "mani" to 54,
        "voter" to 54,
        "last" to 54,
        "sports" to 54,
        "taja" to 54,
        "asha" to 54,
        "akas" to 54,
        "jolokia" to 54,
        "haat" to 54,
        "milk" to 54,
        "kena" to 54,
        "show" to 54,
        "west" to 54,
        "ball" to 54,
        "dikhi" to 54,
        "mexico" to 54,
        "bujhe" to 54,
        "opor" to 54,
        "jiti" to 54,
        "porhai" to 54,
        "nimu" to 54,
        "carbon" to 54,
        "huna" to 54,
        "chance" to 54,
        "berabo" to 54,
        "family" to 54,
        "club" to 54,
        "bamboo" to 54,
        "roast" to 54,
        "doi" to 54,
        "gaan" to 54,
        "neta" to 54,
        "interview" to 54,
        "emergency" to 53,
        "instagram" to 53,
        "firse" to 53,
        "non" to 53,
        "resume" to 53,
        "apni" to 53,
        "hindu" to 53,
        "churi" to 53,
        "hornbill" to 53,
        "whatsapp" to 53,
        "ulabole" to 53,
        "hoijai" to 53,
        "christianity" to 53,
        "porhibi" to 53,
        "ama" to 53,
        "bonabi" to 53,
        "lora" to 53,
        "boil" to 53,
        "najai" to 53,
        "waiter" to 53,
        "ghumai" to 53,
        "nischoi" to 53,
        "ferment" to 53,
        "khabi" to 53,
        "modern" to 53,
        "anda" to 53,
        "protein" to 53,
        "gire" to 53,
        "hindi" to 53,
        "tax" to 53,
        "population" to 53,
        "speed" to 53,
        "tiger" to 53,
        "sri" to 53,
        "likhishe" to 53,
        "kanun" to 53,
        "colony" to 53,
        "conference" to 53,
        "chole" to 53,
        "butter" to 53,
        "status" to 53,
        "strong" to 53,
        "baking" to 53,
        "rule" to 53,
        "charge" to 53,
        "life" to 53,
        "european" to 53,
        "utha" to 53,
        "mehenat" to 53,
        "gorib" to 53,
        "bhabibi" to 53,
        "healthy" to 53,
        "god" to 53,
        "pibi" to 53,
        "is" to 53,
        "help" to 53,
        "green" to 53,
        "janibo" to 53,
        "beer" to 53,
        "model" to 53,
        "ghumabole" to 53,
        "bhutan" to 53,
        "civil" to 53,
        "suwali" to 53,
        "youtube" to 53,
        "saas" to 53,
        "lagabole" to 53,
        "one" to 53,
        "baki" to 53,
        "jura" to 53,
        "ketiaba" to 53,
        "jawan" to 53,
        "secret" to 53,
        "question" to 53,
        "barhi" to 53,
        "nahobo" to 53,
        "sikhai" to 53,
        "gol" to 53,
        "update" to 53,
        "brazil" to 53,
        "korea" to 53,
        "visa" to 53,
        "fire" to 53,
        "bag" to 53,
        "night" to 53,
        "france" to 53,
        "funny" to 53,
        "basket" to 53,
        "hall" to 53,
        "kune" to 53,
        "pass" to 53,
        "body" to 53,
        "nila" to 53,
        "dhori" to 53,
        "napara" to 53,
        "feeling" to 53,
        "white" to 53,
        "day" to 53,
        "hunibi" to 53,
        "off" to 53,
        "copy" to 53,
        "date" to 53,
        "blue" to 53,
        "ulta" to 53,
        "friend" to 53,
        "battery" to 53,
        "tv" to 53,
        "giri" to 53,
        "bachabole" to 53,
        "beach" to 53,
        "pottery" to 53,
        "dhulai" to 53,
        "security" to 52,
        "pi" to 52,
        "germany" to 52,
        "ii" to 52,
        "medical" to 52,
        "nadibi" to 52,
        "tagore" to 52,
        "bengali" to 52,
        "centre" to 52,
        "court" to 52,
        "size" to 52,
        "ticket" to 52,
        "education" to 52,
        "african" to 52,
        "dark" to 52,
        "nuksan" to 52,
        "call" to 52,
        "kutta" to 52,
        "andaj" to 52,
        "italy" to 52,
        "delhi" to 52,
        "minute" to 52,
        "road" to 52,
        "zealand" to 52,
        "khele" to 52,
        "map" to 52,
        "dance" to 52,
        "budget" to 52,
        "chamra" to 52,
        "piye" to 52,
        "scientific" to 52,
        "adhikar" to 52,
        "dhuni" to 52,
        "ros" to 52,
        "action" to 52,
        "pinde" to 52,
        "salary" to 52,
        "vegetarian" to 52,
        "jitishe" to 52,
        "airport" to 52,
        "maaf" to 52,
        "lukai" to 52,
        "wine" to 52,
        "digital" to 52,
        "mi" to 52,
        "tata" to 52,
        "officer" to 52,
        "gym" to 52,
        "desert" to 52,
        "dewal" to 52,
        "theng" to 52,
        "moina" to 52,
        "anime" to 52,
        "ahisele" to 52,
        "bread" to 52,
        "ula" to 52,
        "ice" to 52,
        "clinic" to 52,
        "gyaani" to 52,
        "la" to 52,
        "pattern" to 52,
        "birth" to 52,
        "fayda" to 52,
        "golden" to 52,
        "mondir" to 52,
        "lagebo" to 52,
        "chul" to 52,
        "soup" to 52,
        "buddhism" to 52,
        "jola" to 52,
        "contact" to 52,
        "thank" to 52,
        "hara" to 52,
        "rupees" to 52,
        "drawing" to 52,
        "bisarile" to 52,
        "cup" to 52,
        "man" to 52,
        "bacteria" to 52,
        "literature" to 52,
        "mora" to 52,
        "disele" to 52,
        "dikhabole" to 52,
        "universe" to 52,
        "network" to 52,
        "camera" to 52,
        "jhagara" to 52,
        "farsi" to 52,
        "barhibo" to 51,
        "die" to 51,
        "pork" to 51,
        "solve" to 51,
        "for" to 51,
        "member" to 51,
        "khas" to 51,
        "chuli" to 51,
        "file" to 51,
        "gift" to 51,
        "temple" to 51,
        "newspaper" to 51,
        "example" to 51,
        "teacher" to 51,
        "skin" to 51,
        "choli" to 51,
        "maldives" to 51,
        "plate" to 51,
        "saam" to 51,
        "najana" to 51,
        "weather" to 51,
        "water" to 51,
        "hello" to 51,
        "etuman" to 51,
        "frame" to 51,
        "pressure" to 51,
        "writer" to 51,
        "angami" to 51,
        "pop" to 51,
        "it" to 51,
        "taiyar" to 51,
        "novel" to 51,
        "kina" to 51,
        "project" to 51,
        "bhorta" to 51,
        "bridge" to 51,
        "reason" to 51,
        "chintak" to 51,
        "axone" to 51,
        "mojbut" to 51,
        "support" to 51,
        "policy" to 51,
        "symbol" to 51,
        "rice" to 51,
        "wi" to 51,
        "economy" to 51,
        "gira" to 51,
        "paneer" to 51,
        "kaan" to 51,
        "virus" to 51,
        "mode" to 51,
        "fi" to 51,
        "stoic" to 51,
        "temperature" to 51,
        "electricity" to 51,
        "dikhabi" to 51,
        "puri" to 51,
        "seat" to 51,
        "chuti" to 51,
        "raman" to 51,
        "by" to 51,
        "chicken" to 51,
        "bhari" to 51,
        "baji" to 51,
        "morai" to 51,
        "roj" to 51,
        "kacha" to 51,
        "raati" to 51,
        "korean" to 51,
        "meter" to 51,
        "umor" to 51,
        "renew" to 51,
        "star" to 51,
        "factory" to 51,
        "glass" to 51,
        "puja" to 51,
        "remote" to 51,
        "janibole" to 51,
        "self" to 51,
        "wood" to 51,
        "credit" to 51,
        "death" to 51,
        "land" to 51,
        "japanese" to 51,
        "high" to 51,
        "islam" to 51,
        "print" to 51,
        "ginti" to 51,
        "angh" to 51,
        "pa" to 51,
        "pharak" to 51,
        "hoigole" to 51,
        "second" to 51,
        "document" to 51,
        "birodh" to 51,
        "ghusi" to 51,
        "law" to 51,
        "argentina" to 51,
        "plastic" to 51,
        "player" to 51,
        "dunia" to 51,
        "kath" to 51,
        "hudibole" to 51,
        "dhanyabad" to 51,
        "cover" to 51,
        "rabindranath" to 51,
        "course" to 51,
        "skill" to 51,
        "nokoribi" to 51,
        "powder" to 51,
        "gola" to 51,
        "smart" to 51,
        "faili" to 51,
        "lake" to 51,
        "kolkata" to 51,
        "baje" to 51,
        "lok" to 51,
        "fine" to 51,
        "ajad" to 51,
        "community" to 51,
        "chand" to 51,
        "hr" to 51,
        "record" to 51,
        "komjur" to 51,
        "fry" to 51,
        "planet" to 51,
        "soda" to 51,
        "hatai" to 51,
        "dragon" to 50,
        "gandhi" to 50,
        "middle" to 50,
        "revolution" to 50,
        "hoy" to 50,
        "dokan" to 50,
        "ghambir" to 50,
        "painting" to 50,
        "peace" to 50,
        "sombondho" to 50,
        "silk" to 50,
        "political" to 50,
        "next" to 50,
        "church" to 50,
        "professional" to 50,
        "with" to 50,
        "mocktail" to 50,
        "physical" to 50,
        "jorai" to 50,
        "comedy" to 50,
        "battle" to 50,
        "profile" to 50,
        "parile" to 50,
        "genghis" to 50,
        "western" to 50,
        "base" to 50,
        "oh" to 50,
        "acid" to 50,
        "khorcha" to 50,
        "mumbai" to 50,
        "chehera" to 50,
        "basi" to 50,
        "maida" to 50,
        "yoga" to 50,
        "curry" to 50,
        "block" to 50,
        "union" to 50,
        "pindhe" to 50,
        "piche" to 50,
        "brand" to 50,
        "glaze" to 50,
        "flag" to 50,
        "pipe" to 50,
        "porhe" to 50,
        "moila" to 50,
        "text" to 50,
        "news" to 50,
        "bhara" to 50,
        "flat" to 50,
        "insurance" to 50,
        "phelai" to 50,
        "grammar" to 50,
        "atm" to 50,
        "home" to 50,
        "drive" to 50,
        "central" to 50,
        "mount" to 50,
        "solar" to 50,
        "bagh" to 50,
        "buddhist" to 50,
        "lekhok" to 50,
        "set" to 50,
        "step" to 50,
        "homo" to 50,
        "expert" to 50,
        "advice" to 50,
        "fees" to 50,
        "blood" to 50,
        "wokha" to 50,
        "heart" to 50,
        "ocean" to 50,
        "field" to 50,
        "jaile" to 50,
        "focus" to 50,
        "akela" to 50,
        "muslim" to 50,
        "uthe" to 50,
        "carving" to 50,
        "spicy" to 50,
        "porhise" to 50,
        "christian" to 50,
        "shoot" to 50,
        "joke" to 50,
        "pollution" to 50,
        "dress" to 50,
        "bagan" to 50,
        "julai" to 50,
        "wah" to 50,
        "gussa" to 50,
        "bujhabole" to 50,
        "menu" to 50,
        "ghin" to 50,
        "tower" to 50,
        "bhabibole" to 50,
        "match" to 50,
        "chup" to 50,
        "dikhile" to 50,
        "pindhi" to 50,
        "easy" to 50,
        "hikibi" to 50,
        "house" to 50,
        "fresh" to 50,
        "engineer" to 50,
        "cuisine" to 50,
        "moon" to 50,
        "level" to 50,
        "achanak" to 50,
        "hinduism" to 50,
        "hiki" to 50,
        "old" to 50,
        "center" to 50,
        "tension" to 50,
        "lagile" to 50,
        "daag" to 50,
        "source" to 50,
        "pathabo" to 50,
        "bishoy" to 50,
        "hathiar" to 50,
        "meeting" to 50,
        "wall" to 50,
        "uthai" to 50,
        "bonaisele" to 50,
        "upor" to 50,
        "spanish" to 50,
        "pastry" to 50,
        "kingdom" to 50,
        "case" to 49,
        "fruit" to 49,
        "tani" to 49,
        "atom" to 49,
        "environment" to 49,
        "stadium" to 49,
        "ev" to 49,
        "stand" to 49,
        "commercial" to 49,
        "physics" to 49,
        "nadiye" to 49,
        "rakhile" to 49,
        "organization" to 49,
        "tangkhul" to 49,
        "slip" to 49,
        "aage" to 49,
        "slow" to 49,
        "galat" to 49,
        "cinema" to 49,
        "dabai" to 49,
        "dhul" to 49,
        "st" to 49,
        "year" to 49,
        "permanent" to 49,
        "daan" to 49,
        "khun" to 49,
        "minister" to 49,
        "borbad" to 49,
        "booking" to 49,
        "out" to 49,
        "recommend" to 49,
        "tourist" to 49,
        "skills" to 49,
        "live" to 49,
        "suna" to 49,
        "politics" to 49,
        "loshun" to 49,
        "break" to 49,
        "suntola" to 49,
        "khani" to 49,
        "up" to 49,
        "bisaribi" to 49,
        "shikar" to 49,
        "page" to 49,
        "kot" to 49,
        "letera" to 49,
        "nakora" to 49,
        "fund" to 49,
        "link" to 49,
        "dc" to 49,
        "signature" to 49,
        "oil" to 49,
        "naak" to 49,
        "select" to 49,
        "kute" to 49,
        "piyaj" to 49,
        "matibi" to 49,
        "fermentation" to 49,
        "right" to 49,
        "spelling" to 49,
        "herai" to 49,
        "ok" to 49,
        "birthday" to 49,
        "travel" to 49,
        "mechanic" to 49,
        "dhula" to 49,
        "kata" to 49,
        "december" to 49,
        "mother" to 49,
        "tool" to 49,
        "rate" to 49,
        "identity" to 49,
        "rukhi" to 49,
        "kom" to 49,
        "ghumabi" to 49,
        "sath" to 49,
        "connection" to 49,
        "complex" to 49,
        "kitchen" to 49,
        "deep" to 49,
        "full" to 49,
        "happy" to 49,
        "range" to 49,
        "adha" to 49,
        "sardi" to 49,
        "soft" to 49,
        "ghee" to 49,
        "development" to 49,
        "army" to 49,
        "museum" to 49,
        "aam" to 49,
        "mary" to 49,
        "review" to 49,
        "weaving" to 49,
        "namane" to 49,
        "cholibo" to 49,
        "brahmaputra" to 49,
        "scoby" to 49,
        "experience" to 49,
        "barhai" to 49,
        "azaadi" to 49,
        "square" to 49,
        "chef" to 49,
        "leader" to 49,
        "meghalaya" to 49,
        "russia" to 49,
        "toli" to 49,
        "monsoon" to 49,
        "king" to 49,
        "bake" to 49,
        "kal" to 49,
        "headquarters" to 49,
        "story" to 49,
        "ram" to 49,
        "hill" to 49,
        "cold" to 49,
        "view" to 49,
        "sajai" to 49,
        "eastern" to 49,
        "indonesia" to 49,
        "firing" to 49,
        "ajadi" to 49,
        "hardi" to 49,
        "apple" to 49,
        "log" to 49,
        "dna" to 49,
        "pin" to 49,
        "sesh" to 49,
        "anibo" to 49,
        "diet" to 49,
        "chokra" to 49,
        "jon" to 49,
        "cement" to 49,
        "swadh" to 49,
        "hika" to 49,
        "love" to 49,
        "milibo" to 49,
        "ginger" to 49,
        "steel" to 49,
        "bita" to 49,
        "effect" to 49,
        "bisara" to 49,
        "porhile" to 49,
        "jita" to 49,
        "yeast" to 49,
        "degree" to 49,
        "layer" to 49,
        "spain" to 49,
        "ita" to 49,
        "bazaar" to 49,
        "egypt" to 49,
        "board" to 49,
        "bond" to 49,
        "tamil" to 49,
        "anko" to 49,
        "meaning" to 49,
        "amazon" to 49,
        "addiction" to 49,
        "fat" to 49,
        "driver" to 49,
        "join" to 49,
        "letter" to 49,
        "greece" to 49,
        "petrol" to 48,
        "jaisele" to 48,
        "dushman" to 48,
        "guide" to 48,
        "unique" to 48,
        "united" to 48,
        "aoleang" to 48,
        "permit" to 48,
        "foam" to 48,
        "khulibole" to 48,
        "koisele" to 48,
        "trekking" to 48,
        "sea" to 48,
        "molecule" to 48,
        "hune" to 48,
        "polai" to 48,
        "notice" to 48,
        "iron" to 48,
        "hunile" to 48,
        "bhul" to 48,
        "ghumabo" to 48,
        "gao" to 48,
        "morile" to 48,
        "vaccine" to 48,
        "hacker" to 48,
        "najabo" to 48,
        "box" to 48,
        "singh" to 48,
        "chief" to 48,
        "award" to 48,
        "hude" to 48,
        "roman" to 48,
        "ahom" to 48,
        "dough" to 48,
        "sunday" to 48,
        "bhuk" to 48,
        "chat" to 48,
        "printer" to 48,
        "morning" to 48,
        "section" to 48,
        "gundhai" to 48,
        "triangle" to 48,
        "plane" to 48,
        "boja" to 48,
        "anaros" to 48,
        "serial" to 48,
        "all" to 48,
        "salad" to 48,
        "vote" to 48,
        "safety" to 48,
        "sound" to 48,
        "citizen" to 48,
        "kara" to 48,
        "brush" to 48,
        "nathaki" to 48,
        "financial" to 48,
        "version" to 48,
        "ahikena" to 48,
        "pahori" to 48,
        "friendly" to 48,
        "samaj" to 48,
        "aristotle" to 48,
        "balance" to 48,
        "likhile" to 48,
        "bujhabi" to 48,
        "material" to 48,
        "lagale" to 48,
        "sahi" to 48,
        "bachibole" to 48,
        "ete" to 48,
        "dream" to 48,
        "cycle" to 48,
        "species" to 48,
        "alien" to 48,
        "jolai" to 48,
        "fixed" to 48,
        "rukhabole" to 48,
        "military" to 48,
        "region" to 48,
        "value" to 48,
        "jam" to 48,
        "study" to 48,
        "leave" to 48,
        "cartoon" to 48,
        "lagabi" to 48,
        "download" to 48,
        "bhanga" to 48,
        "aloo" to 48,
        "freedom" to 48,
        "professor" to 48,
        "bean" to 48,
        "ulabo" to 48,
        "longwa" to 48,
        "cotton" to 48,
        "fridge" to 48,
        "emotion" to 48,
        "discount" to 48,
        "artist" to 48,
        "exact" to 48,
        "parking" to 48,
        "gash" to 48,
        "basic" to 48,
        "loisele" to 48,
        "pindhibi" to 48,
        "organic" to 48,
        "mahabharata" to 48,
        "eagle" to 48,
        "khara" to 48,
        "chawal" to 48,
        "drama" to 48,
        "mou" to 48,
        "shillong" to 48,
        "search" to 48,
        "foundation" to 48,
        "yellow" to 48,
        "angur" to 48,
        "rukhai" to 48,
        "dioxide" to 48,
        "mind" to 48,
        "kimchi" to 48,
        "poumai" to 48,
        "chui" to 48,
        "dekha" to 48,
        "bachi" to 48,
        "chemistry" to 48,
        "facility" to 48,
        "edit" to 48,
        "specific" to 48,
        "civilization" to 48,
        "nakhabi" to 48,
        "learning" to 48,
        "hand" to 48,
        "crust" to 48,
        "jongli" to 48,
        "relationship" to 48,
        "settings" to 48,
        "guru" to 48,
        "wheel" to 48,
        "international" to 48,
        "go" to 48,
        "privacy" to 48,
        "vitamin" to 48,
        "my" to 48,
        "sach" to 48,
        "athens" to 48,
        "click" to 48,
        "sorom" to 48,
        "jana" to 48,
        "vietnam" to 48,
        "dr" to 48,
        "agey" to 48,
        "tomato" to 48,
        "bhangi" to 48,
        "kanchenjunga" to 48,
        "gai" to 48,
        "river" to 48,
        "khawa" to 48,
        "alcohol" to 48,
        "aath" to 48,
        "moribole" to 48,
        "azaad" to 48,
        "suggest" to 48,
        "bachabo" to 48,
        "haldi" to 48,
        "dhua" to 48,
        "president" to 48,
        "movement" to 48,
        "late" to 48,
        "electric" to 48,
        "ward" to 48,
        "allergy" to 48,
        "prime" to 48,
        "translate" to 48,
        "mach" to 48,
        "rongin" to 48,
        "ane" to 48,
        "customer" to 48,
        "paka" to 48,
        "colombia" to 48,
        "poem" to 48,
        "dekhabi" to 48,
        "driving" to 48,
        "ramayana" to 48,
        "anishi" to 48,
        "sultan" to 48,
        "ani" to 48,
        "bike" to 48,
        "hikise" to 48,
        "bhabibo" to 48,
        "kurai" to 48,
        "nasile" to 48,
        "mahatma" to 48,
        "saise" to 48,
        "bati" to 48,
        "bollywood" to 48,
        "peru" to 48,
        "uthabole" to 48,
        "structure" to 48,
        "result" to 48,
        "john" to 48,
        "dekhi" to 48,
        "roti" to 48,
        "gali" to 48,
        "korai" to 48,
        "mange" to 48,
        "municipality" to 48,
        "rod" to 48,
        "adruk" to 48,
        "italian" to 48,
        "ground" to 48,
        "hobby" to 48,
        "pathabole" to 47,
        "cultivation" to 47,
        "horror" to 47,
        "pindibole" to 47,
        "connect" to 47,
        "sukhi" to 47,
        "bible" to 47,
        "feet" to 47,
        "noodles" to 47,
        "mission" to 47,
        "counter" to 47,
        "rock" to 47,
        "tree" to 47,
        "baptist" to 47,
        "march" to 47,
        "flight" to 47,
        "tripura" to 47,
        "pindhile" to 47,
        "warrior" to 47,
        "mizoram" to 47,
        "swimming" to 47,
        "sosta" to 47,
        "shadi" to 47,
        "ufo" to 47,
        "director" to 47,
        "tattoo" to 47,
        "knowledge" to 47,
        "bor" to 47,
        "austria" to 47,
        "tawang" to 47,
        "galaxy" to 47,
        "pala" to 47,
        "monastery" to 47,
        "guwahati" to 47,
        "save" to 47,
        "hills" to 47,
        "switch" to 47,
        "portal" to 47,
        "loile" to 47,
        "tar" to 47,
        "reaction" to 47,
        "repair" to 47,
        "pan" to 47,
        "milishe" to 47,
        "ready" to 47,
        "tofu" to 47,
        "dessert" to 47,
        "lakh" to 47,
        "dynasty" to 47,
        "lotha" to 47,
        "install" to 47,
        "limit" to 47,
        "thailand" to 47,
        "mate" to 47,
        "falls" to 47,
        "anjan" to 47,
        "auto" to 47,
        "helmet" to 47,
        "highway" to 47,
        "reading" to 47,
        "industrial" to 47,
        "fit" to 47,
        "traffic" to 47,
        "chandrasekhar" to 47,
        "steam" to 47,
        "municipal" to 47,
        "fried" to 47,
        "sign" to 47,
        "railway" to 47,
        "backup" to 47,
        "namaste" to 47,
        "jonai" to 47,
        "zeliangrong" to 47,
        "safar" to 47,
        "teresa" to 47,
        "soy" to 47,
        "gaming" to 47,
        "cross" to 47,
        "passport" to 47,
        "floor" to 47,
        "crack" to 47,
        "filter" to 47,
        "reality" to 47,
        "first" to 47,
        "head" to 47,
        "fitness" to 47,
        "cancel" to 47,
        "alsi" to 47,
        "anguli" to 47,
        "sleep" to 47,
        "rani" to 47,
        "sugar" to 47,
        "car" to 47,
        "flavour" to 47,
        "persian" to 47,
        "industry" to 47,
        "pie" to 47,
        "chor" to 47,
        "oxygen" to 47,
        "labh" to 47,
        "baanh" to 47,
        "down" to 47,
        "concrete" to 47,
        "purvaj" to 47,
        "burmese" to 47,
        "kine" to 47,
        "poetry" to 47,
        "channel" to 47,
        "stock" to 47,
        "ganga" to 47,
        "based" to 47,
        "batsman" to 47,
        "puka" to 47,
        "murti" to 47,
        "vdb" to 47,
        "medicine" to 47,
        "open" to 47,
        "dhar" to 47,
        "infection" to 47,
        "anise" to 47,
        "experiment" to 47,
        "walk" to 47,
        "salt" to 47,
        "ghasni" to 47,
        "big" to 47,
        "violence" to 47,
        "napabo" to 47,
        "charger" to 47,
        "mahal" to 47,
        "title" to 47,
        "kurishe" to 47,
        "thick" to 47,
        "moral" to 47,
        "customary" to 47,
        "pyramid" to 47,
        "sorry" to 47,
        "chamuch" to 47,
        "ujon" to 47,
        "like" to 47,
        "lord" to 47,
        "mao" to 47,
        "nabhabi" to 47,
        "aizaa" to 47,
        "pile" to 47,
        "chokri" to 47,
        "talent" to 47,
        "phuli" to 47,
        "manage" to 47,
        "gusa" to 47,
        "force" to 47,
        "permission" to 47,
        "ujala" to 47,
        "article" to 47,
        "sumo" to 47,
        "request" to 47,
        "hikibo" to 47,
        "bisare" to 47,
        "subject" to 47,
        "lakri" to 47,
        "memory" to 47,
        "kol" to 47,
        "saile" to 47,
        "republic" to 47,
        "ghura" to 47,
        "epic" to 47,
        "syrup" to 47,
        "har" to 47,
        "narikol" to 47,
        "mix" to 47,
        "season" to 47,
        "kinile" to 47,
        "khuri" to 47,
        "counselor" to 47,
        "turkey" to 47,
        "continent" to 47,
        "fail" to 47,
        "honey" to 47,
        "gun" to 47,
        "napibole" to 47,
        "lion" to 46,
        "feast" to 46,
        "lab" to 46,
        "gura" to 46,
        "islands" to 46,
        "bachibo" to 46,
        "barta" to 46,
        "gangtok" to 46,
        "follow" to 46,
        "reservation" to 46,
        "nadibo" to 46,
        "bache" to 46,
        "ambani" to 46,
        "haddi" to 46,
        "kachari" to 46,
        "root" to 46,
        "long" to 46,
        "perfume" to 46,
        "royal" to 46,
        "mughal" to 46,
        "fort" to 46,
        "shah" to 46,
        "smoking" to 46,
        "accident" to 46,
        "score" to 46,
        "dhoribole" to 46,
        "ahimsa" to 46,
        "human" to 46,
        "aadhaar" to 46,
        "economic" to 46,
        "brown" to 46,
        "left" to 46,
        "lassi" to 46,
        "reject" to 46,
        "dialogue" to 46,
        "duibar" to 46,
        "gupha" to 46,
        "nepali" to 46,
        "kunke" to 46,
        "sikhibole" to 46,
        "plain" to 46,
        "birong" to 46,
        "unit" to 46,
        "architect" to 46,
        "bhori" to 46,
        "nadile" to 46,
        "scan" to 46,
        "income" to 46,
        "victoria" to 46,
        "momo" to 46,
        "thakishe" to 46,
        "indo" to 46,
        "plug" to 46,
        "forest" to 46,
        "rare" to 46,
        "verification" to 46,
        "fm" to 46,
        "global" to 46,
        "emperor" to 46,
        "bandhi" to 46,
        "bowler" to 46,
        "vedas" to 46,
        "kobor" to 46,
        "circle" to 46,
        "krishna" to 46,
        "original" to 46,
        "maram" to 46,
        "gate" to 46,
        "deodorant" to 46,
        "shopping" to 46,
        "cholise" to 46,
        "researcher" to 46,
        "jain" to 46,
        "discipline" to 46,
        "palace" to 46,
        "face" to 46,
        "egg" to 46,
        "risk" to 46,
        "maps" to 46,
        "plateau" to 46,
        "astronomy" to 46,
        "work" to 46,
        "tita" to 46,
        "bujai" to 46,
        "hostel" to 46,
        "dhubo" to 46,
        "nadikhe" to 46,
        "hong" to 46,
        "kong" to 46,
        "loha" to 46,
        "documents" to 46,
        "pindhibole" to 46,
        "friday" to 46,
        "hoikena" to 46,
        "event" to 46,
        "fossil" to 46,
        "sim" to 46,
        "attack" to 46,
        "ngai" to 46,
        "chutney" to 46,
        "waterfall" to 46,
        "pleasure" to 46,
        "dhaki" to 46,
        "portuguese" to 46,
        "soybean" to 46,
        "competition" to 46,
        "ghon" to 46,
        "bech" to 46,
        "confirm" to 46,
        "galti" to 46,
        "cloud" to 46,
        "sida" to 46,
        "sobke" to 46,
        "bangalore" to 46,
        "soviet" to 46,
        "badam" to 46,
        "collection" to 46,
        "classical" to 46,
        "ukhrul" to 46,
        "button" to 46,
        "assistant" to 46,
        "craft" to 46,
        "kamai" to 46,
        "turant" to 46,
        "register" to 46,
        "metal" to 46,
        "chemist" to 46,
        "hemisphere" to 46,
        "nefa" to 46,
        "abhijit" to 46,
        "germs" to 46,
        "afghanistan" to 46,
        "bhuli" to 46,
        "double" to 46,
        "dialect" to 46,
        "super" to 46,
        "natok" to 46,
        "registration" to 46,
        "chile" to 46,
        "login" to 46,
        "site" to 46,
        "eye" to 46,
        "orange" to 46,
        "kombol" to 46,
        "istanbul" to 46,
        "mental" to 46,
        "banerjee" to 46,
        "drain" to 46,
        "mosquito" to 46,
        "gila" to 46,
        "jahaaj" to 46,
        "race" to 46,
        "higher" to 46,
        "berlin" to 46,
        "nichoy" to 46,
        "role" to 46,
        "sahab" to 46,
        "barhibole" to 46,
        "pindha" to 46,
        "guard" to 46,
        "dairy" to 46,
        "paris" to 46,
        "bonale" to 46,
        "actor" to 46,
        "morise" to 46,
        "democracy" to 46,
        "jungle" to 46,
        "add" to 46,
        "bujha" to 46,
        "transport" to 46,
        "gele" to 46,
        "guti" to 46,
        "net" to 46,
        "branch" to 46,
        "payment" to 46,
        "windows" to 46,
        "gala" to 46,
        "serious" to 46,
        "poet" to 46,
        "nigeria" to 46,
        "gravity" to 46,
        "sikhi" to 46,
        "chukri" to 46,
        "classic" to 46,
        "fish" to 46,
        "bebohar" to 46,
        "dhulabi" to 46,
        "sapiens" to 46,
        "greenhouse" to 46,
        "bari" to 46,
        "digha" to 46,
        "mineral" to 46,
        "meditation" to 46,
        "formal" to 46,
        "contractor" to 46,
        "your" to 46,
        "puhor" to 46,
        "koti" to 46,
        "dosti" to 46,
        "enjoy" to 46,
        "iran" to 46,
        "rio" to 46,
        "philosopher" to 46,
        "jowa" to 46,
        "fertilizer" to 46,
        "real" to 46,
        "juta" to 46,
        "pans" to 46,
        "patha" to 46,
        "renaissance" to 46,
        "bisaribo" to 46,
        "atmosphere" to 46,
        "sure" to 46,
        "hosiyar" to 46,
        "confuse" to 46,
        "telescope" to 46,
        "dhaan" to 46,
        "hikile" to 46,
        "nakuri" to 46,
        "people" to 46,
        "miss" to 46,
        "satyarthi" to 46,
        "duitai" to 46,
        "earth" to 46,
        "kailash" to 46,
        "farming" to 46,
        "will" to 46,
        "engineering" to 46,
        "naram" to 46,
        "over" to 46,
        "hala" to 46,
        "covid" to 46,
        "khilai" to 46,
        "korisele" to 46,
        "mars" to 46,
        "subidha" to 46,
        "not" to 46,
        "oven" to 46,
        "apartheid" to 46,
        "bimar" to 46,
        "buddha" to 46,
        "october" to 46,
        "us" to 46,
        "shirt" to 46,
        "bujhabo" to 46,
        "maribole" to 46,
        "active" to 46,
        "everest" to 46,
        "rati" to 46,
        "prani" to 46,
        "concept" to 46,
        "fee" to 46,
        "hi" to 46,
        "choice" to 46,
        "kurabole" to 46,
        "mircha" to 46,
        "tanka" to 46,
        "achar" to 45,
        "pankha" to 45,
        "calligraphy" to 45,
        "bina" to 45,
        "anal" to 45,
        "beauty" to 45,
        "catholic" to 45,
        "hollywood" to 45,
        "consciousness" to 45,
        "andes" to 45,
        "encourage" to 45,
        "switzerland" to 45,
        "darjeeling" to 45,
        "mithun" to 45,
        "taj" to 45,
        "dzukou" to 45,
        "nadu" to 45,
        "exist" to 45,
        "registrar" to 45,
        "bare" to 45,
        "paste" to 45,
        "illegal" to 45,
        "friends" to 45,
        "compare" to 45,
        "coding" to 45,
        "sundarbans" to 45,
        "element" to 45,
        "dahi" to 45,
        "himalayas" to 45,
        "situation" to 45,
        "secondary" to 45,
        "garlic" to 45,
        "publish" to 45,
        "nemu" to 45,
        "wash" to 45,
        "mosque" to 45,
        "topping" to 45,
        "anthem" to 45,
        "jhum" to 45,
        "pisi" to 45,
        "parise" to 45,
        "bad" to 45,
        "past" to 45,
        "mushroom" to 45,
        "ghurai" to 45,
        "offer" to 45,
        "amritsar" to 45,
        "or" to 45,
        "laagi" to 45,
        "committee" to 45,
        "bhangai" to 45,
        "fast" to 45,
        "motor" to 45,
        "religion" to 45,
        "ireland" to 45,
        "programming" to 45,
        "supplies" to 45,
        "negative" to 45,
        "draft" to 45,
        "pawa" to 45,
        "dead" to 45,
        "korabole" to 45,
        "booth" to 45,
        "bihu" to 45,
        "khiamniungan" to 45,
        "plato" to 45,
        "inca" to 45,
        "dubai" to 45,
        "founder" to 45,
        "guarantee" to 45,
        "medal" to 45,
        "besibhaag" to 45,
        "ahanai" to 45,
        "fighter" to 45,
        "portugal" to 45,
        "cookie" to 45,
        "memorial" to 45,
        "tuensang" to 45,
        "cultural" to 45,
        "jainism" to 45,
        "dao" to 45,
        "ambulance" to 45,
        "clear" to 45,
        "espresso" to 45,
        "coral" to 45,
        "brain" to 45,
        "khaise" to 45,
        "bohibole" to 45,
        "nalagibo" to 45,
        "milibole" to 45,
        "stage" to 45,
        "marx" to 45,
        "illuminati" to 45,
        "advertisement" to 45,
        "property" to 45,
        "headhunting" to 45,
        "nakurile" to 45,
        "secretary" to 45,
        "institute" to 45,
        "rich" to 45,
        "million" to 45,
        "jawab" to 45,
        "crispy" to 45,
        "coke" to 45,
        "hole" to 45,
        "algorithm" to 45,
        "jale" to 45,
        "uk" to 45,
        "scholarship" to 45,
        "silent" to 45,
        "england" to 45,
        "punchibole" to 45,
        "garden" to 45,
        "positive" to 45,
        "entry" to 45,
        "norway" to 45,
        "bolivia" to 45,
        "al" to 45,
        "startup" to 45,
        "an" to 45,
        "rongmei" to 45,
        "billion" to 45,
        "ilaj" to 45,
        "construction" to 45,
        "naharibi" to 45,
        "pacific" to 45,
        "blade" to 45,
        "southeast" to 45,
        "daily" to 45,
        "wiring" to 45,
        "indus" to 45,
        "short" to 45,
        "luck" to 45,
        "flower" to 45,
        "qr" to 45,
        "ayna" to 45,
        "malish" to 45,
        "chap" to 45,
        "april" to 45,
        "cocktail" to 45,
        "khasi" to 45,
        "kenya" to 45,
        "spring" to 45,
        "kilometer" to 45,
        "sadharan" to 45,
        "dhubi" to 45,
        "election" to 45,
        "chain" to 45,
        "kabita" to 45,
        "cash" to 44,
        "fiction" to 44,
        "statue" to 44,
        "coconut" to 44,
        "zutho" to 44,
        "shop" to 44,
        "jate" to 44,
        "balu" to 44,
        "territory" to 44,
        "sikh" to 44,
        "neck" to 44,
        "doubt" to 44,
        "shakespeare" to 44,
        "pdf" to 44,
        "northern" to 44,
        "polite" to 44,
        "format" to 44,
        "nisa" to 44,
        "hot" to 44,
        "sub" to 44,
        "mustard" to 44,
        "position" to 44,
        "campus" to 44,
        "bhorai" to 44,
        "hour" to 44,
        "cabbage" to 44,
        "scam" to 44,
        "band" to 44,
        "sticker" to 44,
        "osor" to 44,
        "silicon" to 44,
        "reef" to 44,
        "street" to 44,
        "guesthouse" to 44,
        "namila" to 44,
        "syllable" to 44,
        "tarkari" to 44,
        "daya" to 44,
        "lights" to 44,
        "web" to 44,
        "bohibi" to 44,
        "equator" to 44,
        "dhorjo" to 44,
        "decide" to 44,
        "inverter" to 44,
        "be" to 44,
        "archery" to 44,
        "latte" to 44,
        "howrah" to 44,
        "architecture" to 44,
        "cholabo" to 44,
        "this" to 44,
        "location" to 44,
        "matibole" to 44,
        "pibo" to 44,
        "purpose" to 44,
        "administration" to 44,
        "dekhabole" to 44,
        "wallet" to 44,
        "hikabi" to 44,
        "okay" to 44,
        "best" to 44,
        "robot" to 44,
        "available" to 44,
        "children" to 44,
        "kadam" to 44,
        "jankari" to 44,
        "jimedari" to 44,
        "access" to 44,
        "etia" to 44,
        "nutrients" to 44,
        "soil" to 44,
        "safal" to 44,
        "invest" to 44,
        "charibo" to 44,
        "swagat" to 44,
        "thogai" to 44,
        "pulta" to 44,
        "mutual" to 44,
        "disturb" to 44,
        "motto" to 44,
        "gold" to 44,
        "belt" to 44,
        "duplicate" to 44,
        "jheel" to 44,
        "bajai" to 44,
        "dutch" to 44,
        "leaf" to 44,
        "tukra" to 44,
        "mahila" to 44,
        "chati" to 44,
        "appointment" to 44,
        "pension" to 44,
        "cycling" to 44,
        "planning" to 44,
        "noodle" to 44,
        "things" to 44,
        "pharmacy" to 44,
        "kate" to 44,
        "sacred" to 44,
        "decision" to 44,
        "pink" to 44,
        "solution" to 44,
        "phek" to 44,
        "aboriginal" to 44,
        "heraise" to 44,
        "cafe" to 44,
        "dos" to 44,
        "ghana" to 44,
        "panch" to 44,
        "scotland" to 44,
        "ulaise" to 44,
        "rain" to 44,
        "biology" to 44,
        "script" to 44,
        "ring" to 44,
        "dry" to 44,
        "phati" to 44,
        "longleng" to 44,
        "abar" to 44,
        "ilp" to 44,
        "father" to 44,
        "favourite" to 44,
        "crime" to 44,
        "chana" to 44,
        "viral" to 44,
        "multiply" to 44,
        "maya" to 44,
        "bright" to 44,
        "me" to 44,
        "thak" to 44,
        "lowa" to 44,
        "ghats" to 44,
        "panda" to 44,
        "ratan" to 44,
        "bay" to 44,
        "bikha" to 44,
        "jhaal" to 44,
        "divide" to 44,
        "spider" to 44,
        "eksho" to 44,
        "medium" to 44,
        "nuts" to 44,
        "recycle" to 44,
        "antiperspirant" to 44,
        "maharashtra" to 44,
        "tropical" to 44,
        "mistri" to 44,
        "barhabole" to 44,
        "anti" to 44,
        "dravidian" to 44,
        "biryani" to 44,
        "hike" to 44,
        "journal" to 44,
        "running" to 44,
        "lock" to 44,
        "scheduled" to 44,
        "mara" to 44,
        "ghusibole" to 44,
        "pudina" to 44,
        "store" to 44,
        "do" to 44,
        "gst" to 44,
        "labour" to 44,
        "curd" to 44,
        "hikabole" to 44,
        "method" to 44,
        "malware" to 44,
        "urban" to 44,
        "fa" to 44,
        "ghorolu" to 44,
        "cinnamon" to 44,
        "technique" to 44,
        "towel" to 44,
        "narayan" to 44,
        "najabi" to 44,
        "rajasthan" to 44,
        "success" to 44,
        "komjuri" to 44,
        "name" to 44,
        "single" to 44,
        "pindhibo" to 44,
        "tip" to 44,
        "window" to 44,
        "cave" to 44,
        "basho" to 44,
        "kigo" to 44,
        "dhakka" to 44,
        "prove" to 44,
        "purba" to 44,
        "waka" to 44,
        "goa" to 44,
        "industrialist" to 44,
        "jite" to 44,
        "breakfast" to 44,
        "vitamins" to 44,
        "moksha" to 44,
        "icon" to 44,
        "heaven" to 44,
        "dhalai" to 44,
        "management" to 44,
        "coaching" to 44,
        "chobi" to 44,
        "notes" to 44,
        "nache" to 44,
        "rosun" to 44,
        "aaram" to 44,
        "communication" to 44,
        "girile" to 44,
        "verb" to 44,
        "landing" to 44,
        "renewal" to 44,
        "york" to 44,
        "itanagar" to 44,
        "macedonia" to 44,
        "sen" to 44,
        "london" to 44,
        "item" to 44,
        "jiyai" to 44,
        "poribole" to 44,
        "chicago" to 44,
        "zero" to 44,
        "virtual" to 44,
        "parisele" to 44,
        "buffet" to 44,
        "turkish" to 44,
        "dye" to 44,
        "birla" to 44,
        "speaker" to 44,
        "german" to 44,
        "sun" to 44,
        "hijai" to 44,
        "sewa" to 44,
        "analyze" to 44,
        "compound" to 44,
        "port" to 44,
        "nelson" to 44,
        "enlightenment" to 44,
        "denmark" to 44,
        "animation" to 44,
        "malik" to 44,
        "cemetery" to 44,
        "ziro" to 44,
        "sydney" to 44,
        "ruins" to 44,
        "ana" to 44,
        "angle" to 44,
        "antivirus" to 44,
        "engine" to 44,
        "reception" to 44,
        "dhubole" to 44,
        "kathmandu" to 44,
        "amount" to 44,
        "da" to 44,
        "elephant" to 44,
        "venki" to 44,
        "ramakrishnan" to 44,
        "beijing" to 44,
        "azim" to 44,
        "polo" to 44,
        "half" to 44,
        "amartya" to 44,
        "press" to 44,
        "confucius" to 44,
        "sir" to 44,
        "ed" to 44,
        "bhir" to 44,
        "cell" to 44,
        "fold" to 44,
        "chaya" to 44,
        "chairman" to 44,
        "lizard" to 44,
        "from" to 44,
        "bisar" to 44,
        "superhero" to 44,
        "start" to 44,
        "ji" to 44,
        "final" to 44,
        "manga" to 44,
        "responsibility" to 44,
        "cholaile" to 44,
        "waste" to 44,
        "period" to 44,
        "bluetooth" to 44,
        "move" to 44,
        "jallianwala" to 44,
        "jikun" to 44,
        "matter" to 44,
        "thought" to 44,
        "salah" to 44,
        "hard" to 44,
        "absurd" to 44,
        "sweden" to 44,
        "veg" to 44,
        "pagoda" to 44,
        "confucianism" to 44,
        "chakhesang" to 44,
        "satellite" to 44,
        "economics" to 44,
        "mandela" to 44,
        "universal" to 44,
        "premji" to 44,
        "artificial" to 44,
        "investment" to 44,
        "ssd" to 44,
        "refreshing" to 44,
        "drone" to 44,
        "act" to 44,
        "dekhe" to 44,
        "famine" to 44,
        "ijjot" to 44,
        "apatani" to 44,
        "hathi" to 44,
        "bondhi" to 44,
        "shot" to 44,
        "queen" to 44,
        "taoism" to 44,
        "jaikene" to 44,
        "authority" to 44,
        "biscuit" to 44,
        "track" to 44,
        "scene" to 44,
        "aid" to 44,
        "dto" to 44,
        "funeral" to 44,
        "regular" to 44,
        "bhagyo" to 44,
        "breakup" to 44,
        "mela" to 44,
        "nakoi" to 44,
        "marriage" to 44,
        "malaysia" to 44,
        "senapati" to 44,
        "barhe" to 44,
        "wealth" to 44,
        "seven" to 44,
        "nakha" to 44,
        "air" to 44,
        "fashion" to 44,
        "ad" to 44,
        "zeliang" to 44,
        "thai" to 44,
        "january" to 44,
        "rickshaw" to 44,
        "basketball" to 44,
        "rough" to 44,
        "logical" to 44,
        "tormuj" to 44,
        "namile" to 44,
        "cat" to 44,
        "way" to 44,
        "jhamela" to 44,
        "agriculture" to 44,
        "chithi" to 44,
        "mauka" to 44,
        "cable" to 44,
        "expire" to 44,
        "guinea" to 44,
        "hygiene" to 44,
        "earthquake" to 44,
        "garam" to 44,
        "sumi" to 44,
        "oscar" to 44,
        "burma" to 44,
        "berale" to 44,
        "storage" to 44,
        "tir" to 44,
        "san" to 44,
        "sobhab" to 44,
        "badal" to 44,
        "august" to 44,
        "mangi" to 44,
        "nathakibo" to 44,
        "biyar" to 44,
        "bomb" to 44,
        "ghatna" to 44,
        "nl" to 44,
        "ethiopia" to 44,
        "dikhaise" to 44,
        "wrestling" to 44,
        "literacy" to 44,
        "summary" to 44,
        "census" to 44,
        "tourism" to 44,
        "failai" to 44,
        "forbidden" to 44,
        "bakery" to 44,
        "bisaribole" to 44,
        "recommendation" to 44,
        "server" to 44,
        "hub" to 44,
        "acting" to 44,
        "summer" to 44,
        "song" to 44,
        "condition" to 44,
        "notification" to 44,
        "average" to 44,
        "probiotics" to 44,
        "toka" to 44,
        "sa" to 44,
        "gluten" to 44,
        "ni" to 44,
        "yogurt" to 44,
        "hope" to 44,
        "venezuela" to 44,
        "routine" to 44,
        "meat" to 44,
        "grand" to 44,
        "cholesterol" to 44,
        "jokhom" to 44,
        "nagas" to 44,
        "pack" to 44,
        "whisky" to 44,
        "soya" to 44,
        "logor" to 44,
        "napale" to 44,
        "rum" to 44,
        "khorot" to 44,
        "comment" to 44,
        "statement" to 44,
        "morung" to 44,
        "heritage" to 44,
        "nakobi" to 44,
        "thesis" to 43,
        "ceremony" to 43,
        "sorgo" to 43,
        "jupiter" to 43,
        "stabilizer" to 43,
        "electrician" to 43,
        "sagoli" to 43,
        "ayurveda" to 43,
        "bhagai" to 43,
        "helpline" to 43,
        "umpire" to 43,
        "bone" to 43,
        "tseminyu" to 43,
        "sufi" to 43,
        "sanitizer" to 43,
        "ethics" to 43,
        "rumi" to 43,
        "studio" to 43,
        "chot" to 43,
        "katibole" to 43,
        "device" to 43,
        "phula" to 43,
        "anibi" to 43,
        "drum" to 43,
        "chips" to 43,
        "dimaag" to 43,
        "likhai" to 43,
        "bear" to 43,
        "flour" to 43,
        "cane" to 43,
        "feature" to 43,
        "pindile" to 43,
        "ghar" to 43,
        "guri" to 43,
        "pay" to 43,
        "agent" to 43,
        "butterfly" to 43,
        "kendra" to 43,
        "chenda" to 43,
        "gender" to 43,
        "pradhan" to 43,
        "technical" to 43,
        "sochi" to 43,
        "pwd" to 43,
        "panel" to 43,
        "wheat" to 43
        )
    }

    // Local bigram predictor: matches standard word transitions in Nagamese to recommend the next word instantly
    private val localBigrams: Map<String, List<String>> by lazy {
        mapOf(
        "agote" to listOf("kohima"),
        "ahibi" to listOf("bishi", "moi", "na", "naki", "ahibi", "sath"),
        "ahibole" to listOf("din", "ase", "age", "pare", "thanda", "nimite"),
        "ahile" to listOf("nohoile", "nijor", "he", "ki", "apuni", "tai"),
        "ahise" to listOf("itu", "naki", "aru", "kintu", "motlob", "jun"),
        "aji" to listOf("kali", "laga", "moi", "ki", "bishi", "sapna"),
        "alag" to listOf("alag", "thake", "pora", "ase", "hoi", "jaga"),
        "ami" to listOf("khan", "ase", "jabo", "bhal", "ahise", "duijon"),
        "amikhan" to listOf("laga", "ke", "nijor", "logote", "sob", "logot"),
        "anondo" to listOf("bisaribi", "laga", "aru", "longwa", "pora", "enjoy"),
        "apuni" to listOf("laga", "ke", "nijor", "ki", "tai", "bhal"),
        "aro" to listOf("ki", "bhal", "etu", "moi", "tumi"),
        "aru" to listOf("bishi", "bhal", "tai", "apuni", "sundor", "dusra"),
        "ase" to listOf("na", "aro", "thik", "bhal", "khan", "itu"),
        "asirbad" to listOf("bhi", "aru", "manga", "nimite", "loi", "dibi"),
        "atma" to listOf("ase", "to", "ke", "laga", "jun", "khan"),
        "aur" to listOf("rani"),
        "baba" to listOf("ama", "laga", "bishi", "ke", "pora", "aru"),
        "bajar" to listOf("te", "berabo", "pahar", "jaga", "pabo", "tak"),
        "beli" to listOf("kene"),
        "bemar" to listOf("pora", "laga", "ase", "hoile", "hoi", "nisena"),
        "bepar" to listOf("kuribole", "kurisele", "control", "nimite"),
        "bepari" to listOf("hisab", "aru"),
        "bhai" to listOf("bemar", "laga", "khan", "bhai", "boini", "huni"),
        "bhal" to listOf("ase", "hobo", "manu", "kotha", "hoise", "pora"),
        "bhat" to listOf("to", "bonabole", "logote", "aru"),
        "bhi" to listOf("bishi", "bhal", "ase", "koi", "apuni", "ekta"),
        "bi" to listOf("moi", "thik", "aru", "na", "jiman", "bohut"),
        "bishi" to listOf("bhal", "dangor", "manu", "sundor", "famous", "somoi"),
        "bisi" to listOf("bhal", "kotha", "hobo", "ase", "manu", "ahile"),
        "biswas" to listOf("kore", "kora", "korisile", "ase", "rakhibi", "kuribo"),
        "biswasi" to listOf("thakisele"),
        "boini" to listOf("kunu"),
        "bonai" to listOf("kene", "se", "itu", "dibo", "bishi", "sele"),
        "bujhi" to listOf("bo", "pai", "ase", "jabo", "kene", "napai"),
        "bujhibo" to listOf("napare", "pare", "napara", "paribo", "aru", "naparibo"),
        "bujhise" to listOf("itu"),
        "buri" to listOf("khan"),
        "cha" to listOf("pibole", "te", "logot", "bagan", "tea", "black"),
        "chiti" to listOf("dibi"),
        "chutu" to listOf("chutu", "bacha", "kotha", "jaga", "nakuribi", "jinis"),
        "dada" to listOf("koi", "to", "kohima", "hornbill"),
        "dam" to listOf("to", "kile", "aru", "kiman", "bonai", "kote"),
        "dangor" to listOf("dangor", "aru", "kotha", "kaam", "festival", "sheher"),
        "desh" to listOf("laga", "te", "ase", "pora", "khan", "ke"),
        "dhormo" to listOf("aru"),
        "dibi" to listOf("hoi", "aru", "moi", "apuni", "thik", "itu"),
        "dibo" to listOf("pare", "lage", "napare", "naki", "apuni", "lagibo"),
        "din" to listOf("te", "laga", "tak", "pichete", "to", "bhor"),
        "dise" to listOf("tai", "itu", "eneka", "kintu", "moi", "aiya"),
        "duita" to listOf("bhi", "alag", "desh", "laga", "bishi", "bhag"),
        "dukan" to listOf("te", "pora", "laga", "nohoile", "aru", "to"),
        "dur" to listOf("te", "pora", "ase", "tak", "nohoi", "laga"),
        "dusra" to listOf("manu", "ke", "desh", "laga", "jaga", "logot"),
        "ekta" to listOf("bishi", "bhal", "dangor", "chutu", "ase", "sundor"),
        "eneka" to listOf("hoile", "hoi", "he", "lage", "koi", "kurile"),
        "etu" to listOf("kotha", "bhal", "hobo", "hoise", "nombor", "karone"),
        "gaon" to listOf("laga", "te", "manu", "bura", "pora", "bhitor"),
        "gari" to listOf("chola", "te", "laga", "pora", "pabo", "ase"),
        "ghonta" to listOf("karone", "nisina", "khula", "bhitor"),
        "ghor" to listOf("te", "laga", "manu", "bona", "to", "pora"),
        "girja" to listOf("te", "laga", "ghor", "ase", "aru", "logot"),
        "gorom" to listOf("pani", "din", "hoi", "aru", "dudh", "pora"),
        "hajar" to listOf("hajar", "saal", "bhal", "te", "pora", "purana"),
        "hapta" to listOf("te", "nimite", "nisena", "khotom", "laga", "pichete"),
        "hawa" to listOf("te", "pora", "to", "laga", "pani", "ke"),
        "he" to listOf("bhal", "ase", "sobse", "bishi", "dangor", "thake"),
        "hobo" to listOf("na", "aro", "thik", "pise", "pare", "naki"),
        "hobole" to listOf("pare", "lage", "mon", "bishi", "ki", "chance"),
        "hoi" to listOf("bishi", "jai", "itu", "jabo", "apuni", "aru"),
        "hoile" to listOf("apuni", "ekta", "jitia", "ki", "kunba", "itu"),
        "hoilebi" to listOf("din", "ek", "kaam"),
        "hoise" to listOf("na", "aro", "thik", "pise", "itu", "naki"),
        "huni" to listOf("kene", "bole", "ase", "se", "sabi", "bo"),
        "hunibo" to listOf("pare", "napare", "pabo", "sob"),
        "hunise" to listOf("itu", "hoi", "nohoile", "etu", "moi", "tate"),
        "india" to listOf("laga", "te", "to", "pora", "aru", "ke"),
        "isor" to listOf("ke", "laga", "pora", "logot", "ase", "sob"),
        "itiya" to listOf("dui"),
        "itu" to listOf("pora", "bishi", "to", "nimite", "ke", "ekta"),
        "jaan" to listOf("diya", "jaise"),
        "jabo" to listOf("pare", "lage", "laga", "naki", "aru", "itu"),
        "jaga" to listOf("te", "ase", "pora", "laga", "ke", "nisena"),
        "jaise" to listOf("aiya", "ki", "bishi", "itu", "aru", "naki"),
        "jaldi" to listOf("bhal"),
        "janise" to listOf("ki"),
        "jibon" to listOf("te", "laga", "to", "ke", "aru", "bishi"),
        "jinda" to listOf("jinis", "thaka", "thakibole", "ase", "hoi", "nohoi"),
        "jineka" to listOf("moi", "apuni", "amikhan", "birth", "ekta", "tai"),
        "jisu" to listOf("laga", "ke", "jonom", "duniya", "koise", "hekh"),
        "jun" to listOf("pora", "to", "ke", "laga", "bishi", "apuni"),
        "kaam" to listOf("kore", "te", "to", "kuribo", "kora", "kuribole"),
        "kali" to listOf("bishi", "laga", "sob", "manu", "bohut", "bhal"),
        "kam" to listOf("kurise"),
        "kamabo" to listOf("pare"),
        "kapra" to listOf("pora", "ase", "pindhibi", "te", "aru", "ke"),
        "karone" to listOf("apuni", "tai", "alag", "bhal", "hoi", "bhi"),
        "ke" to listOf("ekta", "bishi", "bhal", "koi", "bhi", "modot"),
        "kene" to listOf("bonai", "ekta", "nijor", "bishi", "apuni", "bhi"),
        "ketiya" to listOf("hoisele", "khotom", "ajad", "azaad", "use", "pora"),
        "khabo" to listOf("lage", "pare", "napare", "aji", "paribo", "parile"),
        "khali" to listOf("ekta", "apuni", "information", "nijor", "kotha", "pet"),
        "khan" to listOf("laga", "ke", "pora", "bishi", "nijor", "bhi"),
        "khelise" to listOf("naki", "moi"),
        "kheti" to listOf("kora", "laga", "te", "kore", "bosti", "nimite"),
        "khotom" to listOf("hoise", "hoi", "howa", "huwa", "hoile", "kuribole"),
        "khusi" to listOf("nai"),
        "ki" to listOf("ase", "hoise", "kotha", "kori", "hobo", "hoile"),
        "kile" to listOf("iman", "eneka", "koi", "manu", "famous", "bishi"),
        "kineka" to listOf("bonai", "kaam", "hobo", "ase", "bhal", "hoi"),
        "kinibo" to listOf("lage", "pare", "paribo", "lagibo", "bhal", "mon"),
        "kinise" to listOf("kintu", "pichete", "bhal", "tai"),
        "kintu" to listOf("moi", "apuni", "bishi", "tai", "itu", "kunba"),
        "kobi" to listOf("hoi", "moi", "apuni", "aru", "bishi", "tai"),
        "kobo" to listOf("pare", "napare", "naparibo", "paribo", "tan", "apuni"),
        "koi" to listOf("kene", "itu", "kilekoile", "ki", "tai", "kintu"),
        "koise" to listOf("moi", "ki", "itu", "tai", "kintu", "joldi"),
        "kora" to listOf("to", "manu", "nai", "time", "aru", "pichete"),
        "kore" to listOf("itu", "kintu", "aru", "naki", "apuni", "tai"),
        "kori" to listOf("ase", "hobo", "thakibo", "pise", "kene", "diye"),
        "kotha" to listOf("ase", "kobo", "bhal", "hoise", "kobi", "nai"),
        "kun" to listOf("ase", "ahise", "hobo", "koise", "tu", "asele"),
        "kunba" to listOf("kunba", "manu", "ke", "bhal", "jaga", "bhabe"),
        "kuri" to listOf("ase", "sabi", "kene", "dibi", "dibo", "diye"),
        "kuribo" to listOf("pare", "lage", "napare", "apuni", "paribo", "itu"),
        "laga" to listOf("kotha", "sobse", "ekta", "naam", "kaam", "bishi"),
        "lage" to listOf("hoi", "itu", "naki", "apuni", "aru", "moi"),
        "lagibo" to listOf("pare", "itu", "aru", "naki", "nohoile", "moi"),
        "lagise" to listOf("moi", "pichete", "apuni", "hoi", "bhal", "tai"),
        "lamba" to listOf("somoi", "aru", "ase", "nodi", "saas", "lamba"),
        "likhi" to listOf("dibo", "kene", "dibi", "rakhibi", "lobi", "dile"),
        "likhibo" to listOf("pare", "lage", "apuni", "proshno", "napare", "mon"),
        "likhise" to listOf("itu", "tai", "vedas", "jun", "koi", "purana"),
        "lobo" to listOf("pare", "lage", "napare", "lagibo", "besi", "para"),
        "logot" to listOf("kotha", "mili", "milai", "lorai", "bishi", "jura"),
        "loise" to listOf("itu", "eneka", "dhanyabaad", "bishi", "kintu", "ki"),
        "ma" to listOf("baba", "ki", "ase", "to", "motlob", "ke"),
        "manu" to listOf("khan", "logote", "bhal", "ase", "pora", "ke"),
        "mati" to listOf("te", "laga", "ke", "pora", "bhitor", "tu"),
        "matibo" to listOf("pare", "lage", "lagibo", "apuni", "itcha", "naki"),
        "misa" to listOf("kotha", "khobor", "koi", "itu", "pora", "koise"),
        "moi" to listOf("ase", "jabo", "bhal", "ahise", "khabo", "kobo"),
        "mon" to listOf("ase", "te", "laga", "dangor", "dukh", "pora"),
        "morom" to listOf("pora", "kora", "kore", "aru", "para", "laga"),
        "mukh" to listOf("te", "pora", "to", "dhulai", "gundhai", "dhulabi"),
        "na" to listOf("nai", "khai", "biya", "hoi", "ahe", "moi"),
        "naam" to listOf("kobi", "to", "ase", "ki", "kobo", "te"),
        "nagaland" to listOf("manu", "pora", "bhal", "te", "ase"),
        "nai" to listOf("kintu", "apuni", "moi", "itu", "eneka", "sob"),
        "naki" to listOf("hoi", "moi", "nohoi", "bishi", "itu", "judi"),
        "naya" to listOf("din"),
        "nijor" to listOf("nijor", "ke", "mon", "pora", "kaam", "bhal"),
        "nimite" to listOf("bishi", "bhal", "ekta", "apuni", "tai", "he"),
        "nisena" to listOf("ki", "ase", "he", "lage", "bishi", "dikhe"),
        "nisina" to listOf("ase", "he", "lobo", "te", "dangor", "use"),
        "nodi" to listOf("to", "te", "laga", "kinar", "ase", "pora"),
        "nohoile" to listOf("kunba", "apuni", "bishi", "bhal", "notun", "alag"),
        "notun" to listOf("jinis", "notun", "idea", "pora", "sathi", "manu"),
        "olop" to listOf("olop", "somoi", "kobi", "komti", "alag", "tan"),
        "paap" to listOf("naki", "korise", "koi", "dhulai", "lage", "nalage"),
        "pabo" to listOf("pare", "hoi", "apuni", "naki", "karone", "moi"),
        "pahar" to listOf("laga", "uporte", "te", "aru", "to", "ase"),
        "pai" to listOf("itu", "jabo", "aru", "naki", "kintu", "apuni"),
        "paise" to listOf("moi", "itu", "apuni", "naki", "ki", "aru"),
        "pare" to listOf("hoi", "kintu", "apuni", "moi", "itu", "nohoile"),
        "path" to listOf("bonabo"),
        "pathar" to listOf("ase", "te", "plateau"),
        "pichete" to listOf("tai", "apuni", "aru", "itu", "he", "ki"),
        "pise" to listOf("naki", "jineka"),
        "pobitro" to listOf("jaga", "kitab", "sheher", "janwar", "mane", "aru"),
        "pora" to listOf("he", "bishi", "bhi", "bona", "bonai", "apuni"),
        "poribo" to listOf("design"),
        "prithibi" to listOf("laga", "ke", "te", "to", "pora", "bishi"),
        "probhu" to listOf("jisu"),
        "purana" to listOf("somoi", "aru", "din", "manu", "greek", "naam"),
        "rakhi" to listOf("kene", "le", "dibi", "dile", "dibo", "diya"),
        "rakhibi" to listOf("aru", "itu", "titia", "bhal", "moi", "tai"),
        "rakhibo" to listOf("pare", "lage", "mon", "itu", "bhal", "apuni"),
        "rakhise" to listOf("moi", "next", "naki", "aiya"),
        "rasta" to listOf("te", "ase", "pora", "bhal", "dikhai", "laga"),
        "rat" to listOf("bhor"),
        "rong" to listOf("to", "laga", "birong", "pora", "ki", "thake"),
        "sabun" to listOf("pora", "aru", "laga", "nisena", "pani", "bhal"),
        "sador" to listOf("to", "ki"),
        "safa" to listOf("hoi", "pani"),
        "school" to listOf("te", "ase", "aru", "to", "college", "laga"),
        "shakti" to listOf("dibo", "ahibo", "ase", "chance"),
        "sidha" to listOf("kore", "ahibo", "nohoi", "line", "jaga", "kintu"),
        "sob" to listOf("manu", "mili", "jinis", "laga", "desh", "ke"),
        "sobse" to listOf("dangor", "bhal", "bishi", "purana", "untcha", "poila"),
        "somoi" to listOf("te", "nimite", "lage", "tak", "laga", "pora"),
        "son" to listOf("of", "panch", "thakise"),
        "sosa" to listOf("kotha", "example", "interest", "kobi"),
        "suraj" to listOf("laga", "aru", "sun"),
        "tai" to listOf("ase", "ahise", "koise", "jabo", "bisi", "hobo"),
        "taike" to listOf("ekta", "bhal", "khobor", "kobi", "support", "direct"),
        "taikhan" to listOf("laga", "ke", "pora", "bishi", "he", "ki"),
        "taka" to listOf("to", "nisina", "nohoile", "kineka"),
        "te" to listOf("bishi", "ki", "ase", "thaka", "bhi", "ekta"),
        "thaka" to listOf("karone", "ekta", "to", "manu", "somoi", "bishi"),
        "thake" to listOf("aru", "itu", "kintu", "apuni", "bishi", "naki"),
        "thakibi" to listOf("aru", "itu", "nohoile", "tai", "moi", "pichete"),
        "thakibo" to listOf("pare", "lage", "itu", "apuni", "he", "tate"),
        "thakise" to listOf("tai", "itu", "naki", "kintu", "aru", "tati"),
        "thanda" to listOf("din", "hoi", "pani", "hawa", "jaga", "thake"),
        "tinehoile" to listOf("apuni"),
        "to" to listOf("bishi", "hoile", "ekta", "ki", "bhal", "apuni"),
        "toi" to listOf("ke", "pora", "moike", "laga", "ketiabi", "bhabe"),
        "tumi" to listOf("ase", "ki", "jabo", "kobo", "keneka", "ahise"),
        "uporte" to listOf("depend", "bishi", "ekta", "ase", "he", "biswas"),
        "uthibo" to listOf("pare", "napare", "aru")
        )
    }

    /**
     * Attempts to fetch cached next-word suggestions from memory
     */
    fun getCachedSuggestions(contextKey: String): List<String>? {
        synchronized(geminiCache) {
            val cached = geminiCache[contextKey]
            if (cached != null) {
                Log.d("OfflineEngine", "Cache hit for '$contextKey': $cached")
            }
            return cached
        }
    }

    /**
     * Stores successful predictions from Gemini in memory for zero-latency reuse
     */
    fun cacheSuggestions(contextKey: String, suggestions: List<String>) {
        if (suggestions.isEmpty()) return
        synchronized(geminiCache) {
            geminiCache[contextKey] = suggestions
            Log.d("OfflineEngine", "Cached '$contextKey' -> $suggestions")
        }
    }

    /**
     * Dynamically registers a word typed by the user to personalize matches
     */
    fun learnWord(word: String) {
        val w = word.trim().lowercase()
        // Skip too short, too long, or non-alphabet strings
        if (w.length <= 1 || w.length > 20 || w.any { !it.isLetter() }) return
        
        // Skip if already a high-ranking dictionary word to save space
        if (localDictionary.containsKey(w) && (localDictionary[w] ?: 0) > 40) return

        synchronized(userWords) {
            val count = userWords[w] ?: 0
            userWords[w] = count + 1
            Log.d("OfflineEngine", "Learned word: '$w' (Count: ${count + 1})")
        }
    }

    /**
     * Capped dynamic bigram learning (limits to 5 transitions per starting word)
     */
    fun learnBigram(lastWord: String, currentWord: String) {
        val lw = lastWord.trim().lowercase()
        val cw = currentWord.trim().lowercase()
        
        if (lw.length <= 1 || lw.length > 20 || lw.any { !it.isLetter() }) return
        if (cw.length <= 1 || cw.length > 20 || cw.any { !it.isLetter() }) return

        synchronized(userBigrams) {
            val transitionMap = userBigrams.getOrPut(lw) { mutableMapOf() }
            val count = transitionMap[cw] ?: 0
            transitionMap[cw] = count + 1

            // Cap entries to 5 transitions per starting word to prevent memory leaks
            if (transitionMap.size > 5) {
                val lowestEntry = transitionMap.minByOrNull { it.value }
                if (lowestEntry != null) {
                    transitionMap.remove(lowestEntry.key)
                }
            }
            Log.d("OfflineEngine", "Learned bigram: '$lw' -> '$cw' (Weight: ${transitionMap[cw]})")
        }
    }

    /**
     * Capped Damerau-Levenshtein edit distance calculation (returns 99 if distance > 1)
     */
    fun getEditDistance(s1: String, s2: String): Int {
        val len1 = s1.length
        val len2 = s2.length
        if (Math.abs(len1 - len2) > 1) return 99

        if (s1 == s2) return 0
        if (len1 == 0) return len2
        if (len2 == 0) return len1

        if (len1 == len2) {
            var diffs = 0
            var firstDiffIndex = -1
            for (i in 0 until len1) {
                if (s1[i] != s2[i]) {
                    diffs++
                    if (diffs > 2) return 99
                    if (firstDiffIndex == -1) {
                        firstDiffIndex = i
                    } else if (diffs == 2) {
                        val j = firstDiffIndex
                        if (!(s1[i] == s2[j] && s1[j] == s2[i] && i == j + 1)) {
                            return 99
                        }
                    }
                }
            }
            if (diffs == 1) return 1
            if (diffs == 2) return 1
            return 99
        } else {
            val (shorter, longer) = if (len1 < len2) s1 to s2 else s2 to s1
            var i = 0
            var j = 0
            var diffs = 0
            while (i < shorter.length && j < longer.length) {
                if (shorter[i] != longer[j]) {
                    diffs++
                    if (diffs > 1) return 99
                    j++
                } else {
                    i++
                    j++
                }
            }
            return 1
        }
    }

    /**
     * Performs instant local prefix-matching for actively-typing autocomplete (0ms delay)
     * Backfills suggestions with fuzzy candidates when exact matches are fewer than 3
     */
    fun getPrefixMatches(prefix: String): List<String> {
        val p = prefix.trim().lowercase()
        if (p.isEmpty()) return emptyList()

        val candidates = mutableListOf<Pair<String, Int>>()

        // 1. Check user-typed words and give them a priority weight boost (exact matches)
        synchronized(userWords) {
            for ((word, freq) in userWords) {
                if (word.startsWith(p)) {
                    candidates.add(word to (freq * 50 + 100))
                }
            }
        }

        // 2. Fetch exact matches from local precompiled vocabulary
        for ((word, freq) in localDictionary) {
            if (word.startsWith(p)) {
                candidates.add(word to freq)
            }
        }

        // Remove duplicates for exact matches, taking the highest frequency ranking
        val uniqueCandidates = candidates
            .groupBy { it.first }
            .map { entry -> entry.key to entry.value.maxOf { it.second } }
            .toMutableList()

        // 3. Backfill with fuzzy matches if we have fewer than 3 exact suggestions
        if (uniqueCandidates.size < 3) {
            val exactWordsSet = uniqueCandidates.map { it.first }.toSet()
            val fuzzyCandidates = mutableListOf<Pair<String, Int>>()

            // Check userWords for fuzzy prefix matches
            synchronized(userWords) {
                for ((word, freq) in userWords) {
                    if (word in exactWordsSet) continue
                    val target = if (word.length >= p.length) word.take(p.length) else word
                    if (getEditDistance(p, target) <= 1) {
                        val baseWeight = freq * 50 + 100
                        fuzzyCandidates.add(word to Math.max(1, baseWeight - 30))
                    }
                }
            }

            // Check local precompiled dictionary for fuzzy prefix matches
            for ((word, freq) in localDictionary) {
                if (word in exactWordsSet) continue
                val target = if (word.length >= p.length) word.take(p.length) else word
                if (getEditDistance(p, target) <= 1) {
                    fuzzyCandidates.add(word to Math.max(1, freq - 30))
                }
            }

            // Group fuzzy candidates and add to uniqueMatches
            val uniqueFuzzy = fuzzyCandidates
                .groupBy { it.first }
                .map { entry -> entry.key to entry.value.maxOf { it.second } }

            uniqueCandidates.addAll(uniqueFuzzy)
        }

        // 4. Group, sort by descending weight, and take top 3 items
        val result = uniqueCandidates
            .groupBy { it.first }
            .map { entry -> entry.key to entry.value.maxOf { it.second } }
            .sortedByDescending { it.second }
            .map { it.first }
            .take(3)
            
        Log.d("OfflineEngine", "Prefix matches for '$p' (exact/fuzzy): $result")
        return result
    }

    /**
     * Performs instant local next-word bigram prediction (0ms delay)
     * Prioritizes learned user transitions and merges them with precompiled ones
     */
    fun getLocalNextWordPredictions(lastWord: String): List<String> {
        val lw = lastWord.trim().lowercase()
        if (lw.isEmpty()) return getPopularWords()

        val candidates = LinkedHashSet<String>()

        // 1. Fetch user-learned transitions first (gives them priority)
        synchronized(userBigrams) {
            val userTrans = userBigrams[lw]
            if (userTrans != null) {
                val sortedUserTrans = userTrans.entries
                    .sortedByDescending { it.value }
                    .map { it.key }
                candidates.addAll(sortedUserTrans)
            }
        }

        // 2. Fetch precompiled next-word bigrams
        val precompiled = localBigrams[lw]
        if (precompiled != null) {
            candidates.addAll(precompiled)
        }

        // Keep only top 3 unique predictions
        val result = candidates.take(3).toList()
        if (result.isNotEmpty()) {
            Log.d("OfflineEngine", "Dynamic predictions for '$lw': $result")
            return result
        }

        // 3. Fallback to general popular words (filtered to make sure we don't repeat the same word)
        val fallback = getPopularWords().filter { it != lw }.take(3)
        Log.d("OfflineEngine", "Fallback transitions for '$lw': $fallback")
        return fallback
    }

    /**
     * Standard startup/fallback suggestion set
     */
    fun getPopularWords(): List<String> {
        return listOf("moi", "tumi", "ase")
    }
}
